/**
 * AVIATION_REFERENCES -- generated by @ab/hangar-sync.
 *
 * DO NOT EDIT BY HAND. Authoritative edits happen via the hangar
 * `/glossary` UI; the sync job writes the TOML seed and regenerates
 * this file in the same commit. Manual edits here will be clobbered by
 * the next sync.
 *
 * Field order + optional-field presence are deterministic so the file
 * diffs cleanly. To add a field, update the emit script, not this
 * file.
 */

import { registerReferences } from '../registry';
import type { Reference } from '../schema/reference';

export const AVIATION_REFERENCES: readonly Reference[] = [
	{
		id: 'test-2n3qpdxpmbfp-ref-create',
		displayName: 'test-2n3qpdxpmbfp-ref-create',
		aliases: [
			'alt-1',
		],
		paraphrase: 'initial body',
		tags: 		{
			sourceType: 'cfr',
			aviationTopic: [
				'regulations',
			],
			flightRules: 'both',
			knowledgeKind: 'reference',
		},
		sources: [],
		related: [],
	},
];

// Register at module load so the registry is populated before any consumer
// imports it.
registerReferences(AVIATION_REFERENCES);
