import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { generateSectionalThumbnail } from './thumbnail';

const TMP = join(import.meta.dirname, '__tmp_thumbnail__');

async function freshTmp() {
	await rm(TMP, { recursive: true, force: true });
	await mkdir(TMP, { recursive: true });
}

function tinyJpegBytes(): Uint8Array {
	// Minimal valid-enough JPEG header + body; never decoded, just written.
	return new Uint8Array([0xff, 0xd8, 0xff, 0xe0, 0, 16, 74, 70, 73, 70, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0xff, 0xd9]);
}

async function fakeArchive(): Promise<string> {
	const p = join(TMP, 'chart.zip');
	await writeFile(p, 'ZIP');
	return p;
}

describe('generateSectionalThumbnail', () => {
	beforeEach(freshTmp);
	afterEach(async () => rm(TMP, { recursive: true, force: true }));

	it('uses forceBytes when provided (test-only fast path)', async () => {
		const archive = await fakeArchive();
		const outPath = join(TMP, 'out', 'thumb.jpg');
		const result = await generateSectionalThumbnail({
			archivePath: archive,
			outPath,
			recordedPath: 'data/sources/sectional/x/2026-03-21/thumb.jpg',
			forceBytes: tinyJpegBytes(),
			probeTool: async () => false,
		});
		expect(result.generator).toBe('gdal_translate');
		expect(result.thumbnailSizeBytes).toBe(tinyJpegBytes().length);
		const onDisk = await readFile(outPath);
		expect(onDisk.length).toBe(tinyJpegBytes().length);
	});

	it('uses gdal_translate when it is on PATH and exits 0', async () => {
		const archive = await fakeArchive();
		const outPath = join(TMP, 'out', 'thumb.jpg');
		const bytes = tinyJpegBytes();
		const result = await generateSectionalThumbnail({
			archivePath: archive,
			outPath,
			recordedPath: 'data/sources/sectional/x/ed/thumb.jpg',
			probeTool: async (cmd) => cmd === 'gdal_translate',
			runCommand: async ({ cmd }) => {
				// Simulate gdal writing to the temp path (cmd last arg).
				const tmpOut = cmd[cmd.length - 1];
				if (typeof tmpOut === 'string') await writeFile(tmpOut, bytes);
				return 0;
			},
		});
		expect(result.generator).toBe('gdal_translate');
		expect(result.thumbnailSizeBytes).toBe(bytes.length);
	});

	it('falls back to sips when GDAL is absent', async () => {
		const archive = await fakeArchive();
		const outPath = join(TMP, 'out', 'thumb.jpg');
		const bytes = tinyJpegBytes();
		const result = await generateSectionalThumbnail({
			archivePath: archive,
			outPath,
			recordedPath: 'data/sources/sectional/x/ed/thumb.jpg',
			probeTool: async (cmd) => cmd === 'sips',
			runCommand: async ({ cmd }) => {
				// sips --out is next-to-last
				const outIdx = cmd.indexOf('--out');
				const tmpOut = outIdx >= 0 ? cmd[outIdx + 1] : undefined;
				if (typeof tmpOut === 'string') await writeFile(tmpOut, bytes);
				return 0;
			},
		});
		expect(result.generator).toBe('sips');
	});

	it('degrades to unavailable when neither tool is on PATH', async () => {
		const archive = await fakeArchive();
		const outPath = join(TMP, 'out', 'thumb.jpg');
		const result = await generateSectionalThumbnail({
			archivePath: archive,
			outPath,
			recordedPath: 'data/sources/sectional/x/ed/thumb.jpg',
			probeTool: async () => false,
			runCommand: async () => 0,
		});
		expect(result.generator).toBe('unavailable');
		expect(result.thumbnailSizeBytes).toBe(0);
		// Placeholder file written so files browser does not 404.
		const onDisk = await readFile(outPath);
		expect(onDisk.length).toBe(0);
	});

	it('throws when the generated bytes exceed the size budget', async () => {
		const archive = await fakeArchive();
		const outPath = join(TMP, 'out', 'thumb.jpg');
		const bigBytes = new Uint8Array(512 * 1024);
		await expect(
			generateSectionalThumbnail({
				archivePath: archive,
				outPath,
				recordedPath: 'data/sources/sectional/x/ed/thumb.jpg',
				forceBytes: bigBytes,
				probeTool: async () => false,
			}),
		).rejects.toThrow(/exceeds budget/);
	});

	it('records sha256 of the written bytes', async () => {
		const archive = await fakeArchive();
		const outPath = join(TMP, 'out', 'thumb.jpg');
		const result = await generateSectionalThumbnail({
			archivePath: archive,
			outPath,
			recordedPath: 'data/sources/sectional/x/ed/thumb.jpg',
			forceBytes: tinyJpegBytes(),
			probeTool: async () => false,
		});
		// Deterministic sha for the tinyJpegBytes literal.
		expect(result.thumbnailSha256).toMatch(/^[a-f0-9]{64}$/);
	});
});
