// Hangar BC -- registry CRUD, job pipelines, source ingest, users directory.
// Owns the `hangar.*` schema and every Drizzle query that touches it.

export {
	type ActorSearchHit,
	AUDIT_ACTOR_SYSTEM,
	type AuditEntriesPage,
	type AuditEntryDetail,
	type AuditEntryRow,
	type AuditFilters,
	buildAuditWhere,
	clampAuditLimit,
	type DecodedAuditCursor,
	decodeAuditCursor,
	encodeAuditCursor,
	getActorById,
	getAuditEntry,
	isLikelyAuthId,
	listAuditEntries,
	resolveActorForChip,
	searchActorIds,
} from './audit-queries';
export { HANGAR_BLOB_DIR, resolveHangarBlobRoot } from './blob-root';
export {
	countAllJobs,
	countLiveReferences,
	countLiveSources,
	listLiveSources,
} from './dashboard-queries';
export type { FetchHtmlFn } from './edition-stub';
export { makeStubFetchHtml, withEditionStub } from './edition-stub';
export {
	type FieldErrors,
	getAll,
	getOptionalString,
	getString,
	parseJsonObject,
	splitCommaList,
	splitNewlineOrComma,
	zodIssuesToFieldErrors,
} from './form-helpers';
export {
	aliasesSchema,
	type BinaryVisualLocatorParsed,
	binaryVisualLocatorSchema,
	citationSchema,
	displayNameSchema,
	keywordsSchema,
	outboundUrlSchema,
	paraphraseSchema,
	type ReferenceInputParsed,
	referenceIdSchema,
	referenceSchema,
	relatedSchema,
	type SourceInputParsed,
	sourceFormatSchema,
	sourceIdSchema,
	sourceSchema,
	tagsSchema,
} from './form-schemas';
export {
	getActiveJobForTarget,
	getLatestCompleteJobByKind,
	getLatestCompleteJobForTarget,
	listRecentJobsForTarget,
	listRunningJobs,
} from './jobs-queries';
export {
	formDataToInitial,
	parseCitations,
	type ReferenceValidationFailure,
	type ValidatedReference,
	validateReferenceForm,
} from './reference-form';
export { EMPTY_REFERENCE_INITIAL, type ReferenceFormInitial } from './reference-form-types';
export {
	createReference,
	createSource,
	getReference,
	getReferenceSummary,
	getSource,
	type ListReferencesOptions,
	type ListReferencesResult,
	type ListSourcesOptions,
	type ListSourcesResult,
	listReferences,
	listSources,
	NotFoundError,
	type ReferenceInput,
	type ReferenceSummaryRow,
	type ReferenceTagsInput,
	RevConflictError,
	referenceDescSortByUpdated,
	type SourceCitationInput,
	type SourceInput,
	softDeleteReference,
	softDeleteSource,
	sourceDescSortByUpdated,
	updateReference,
	updateSource,
} from './registry';
export {
	type HangarReferenceRow,
	type HangarSourceEdition,
	type HangarSourceMedia,
	type HangarSourceRow,
	type HangarSyncLogRow,
	hangarReference,
	hangarSchema,
	hangarSource,
	hangarSyncLog,
	type NewHangarReferenceRow,
	type NewHangarSourceRow,
	type NewHangarSyncLogRow,
} from './schema';
export { assertRevSnapshot, parseRevSnapshot, type RevSnapshot, RevSnapshotSchema } from './schema-types';
export {
	type ArchiveEntry,
	type ArchiveReaderFn,
	type BinaryVisualFetchOptions,
	type DbUpdaterFn,
	type DownloaderFn,
	formatEditionDiff,
	handleBinaryVisualFetch,
	type LocatorShape,
	type ResolverFn,
	runSectionalFetch,
	SECTIONAL_CADENCE_DAYS,
	type SectionalFetchHooks,
	type SectionalFetchInput,
	type SectionalFetchOutcome,
	type ThumbnailFn,
} from './source-fetch';
export {
	type OutboundUrlValidationFailure,
	type OutboundUrlValidationOk,
	type OutboundUrlValidationResult,
	type SourceValidationFailure,
	sourceFormDataToInitial,
	type ValidatedSource,
	validateSourceForm,
	validateSourceFormUrls,
} from './source-form';
export { EMPTY_SOURCE_INITIAL, type SourceFormInitial } from './source-form-types';
export {
	type FetchHandlerOptions,
	makeBuildHandler,
	makeDiffHandler,
	makeExtractHandler,
	makeFetchHandler,
	makeUploadHandler,
	makeValidateHandler,
	nodeSpawnRunner,
	REPO_ROOT,
	type SourceJobOptions,
	type SpawnResult,
	type SpawnRunner,
	type TargetedSourcePayload,
} from './source-jobs';
export {
	getSeedSource,
	getSeedSourcesByType,
	isSeedSourceDownloaded,
	PENDING_DOWNLOAD,
	SOURCES as SEED_SOURCES,
} from './source-seed-registry';
export type { UploadHandlerOptions, UploadJobPayload } from './upload-handler';
export {
	archiveFilename,
	destFilename,
	extensionOf,
	isNoChange,
	pickArchivesToPrune,
} from './upload-helpers';
export {
	type BanUserFormInput,
	BanUserInputSchema,
	type RevokeAllUserSessionsFormInput,
	RevokeAllUserSessionsInputSchema,
	type RevokeUserSessionFormInput,
	RevokeUserSessionInputSchema,
	type SetUserRoleFormInput,
	SetUserRoleInputSchema,
	type UnbanUserFormInput,
	UnbanUserInputSchema,
} from './user-write-schemas';
export {
	type AdminAuthApi,
	type AdminAuthBundle,
	assertNotLastAdmin,
	assertSelfTargetAllowed,
	type BanUserActionInput,
	BetterAuthApiError,
	banUserAction,
	expiresAtToBanExpiresIn,
	LastAdminError,
	type RevokeAllUserSessionsInput,
	type RevokeUserSessionInput,
	revokeAllUserSessions,
	revokeUserSession,
	SelfTargetForbiddenError,
	type SelfTargetGuardOp,
	type SetUserRoleInput,
	setUserRole,
	type UnbanUserActionInput,
	unbanUserAction,
} from './user-writes';
export {
	buildUserSearchWhere,
	countUserSessions,
	countUsersByRole,
	getUser,
	type ListUsersOptions,
	listRecentUserAudits,
	listRecentUserSessions,
	listUsers,
	narrowRole,
	USER_DETAIL_AUDIT_LIMIT,
	USER_DETAIL_SESSION_LIMIT,
	USERS_LIST_LIMIT,
	type UserAuditRow,
	type UserDirectoryRow,
	type UserSessionRow,
} from './users';
