import {
	APPEARANCE_COOKIE,
	injectPreHydrationScript,
	parseAppearancePreference,
	readThemeFromCookies,
} from '@ab/themes';
import { PRE_HYDRATION_SCRIPT } from '@ab/themes/generated/pre-hydration';
import type { Handle } from '@sveltejs/kit';
import { building } from '$app/environment';

const REQUEST_ID_PATTERN = /^[a-zA-Z0-9_-]{1,64}$/;
const REQUEST_ID_HEADER = 'x-request-id';

function resolveRequestId(req: Request): string {
	const raw = req.headers.get(REQUEST_ID_HEADER);
	return raw && REQUEST_ID_PATTERN.test(raw) ? raw : crypto.randomUUID();
}

/**
 * Sim hooks.
 *
 * Sim has no auth and no DB writes, so the handler is intentionally
 * minimal: it reads the appearance and theme cookies into `event.locals`
 * (so the layout server load can echo them to the client) and substitutes
 * the pre-hydration script body into `app.html` via `transformPageChunk`.
 *
 * The shared script body is generated by `bun themes:emit` from the
 * theme registry and lives at `@ab/themes/generated/pre-hydration`. The
 * substitution rule (`%theme-pre-hydration%` placeholder -> body) lives
 * in `@ab/themes` so all three apps stay in sync without duplicating it.
 */
export const handle: Handle = async ({ event, resolve }) => {
	if (building) return resolve(event);

	const requestId = resolveRequestId(event.request);
	event.locals.requestId = requestId;
	event.locals.appearance = parseAppearancePreference(event.cookies.get(APPEARANCE_COOKIE));
	event.locals.theme = readThemeFromCookies(event.cookies);

	const response = await resolve(event, {
		transformPageChunk: ({ html }) => injectPreHydrationScript(html, PRE_HYDRATION_SCRIPT),
	});

	try {
		response.headers.set(REQUEST_ID_HEADER, requestId);
	} catch {
		// Some response types (streaming/binary) have frozen headers; skip silently.
	}

	return response;
};
