/**
 * Spike 01 -- Layer 3 AIRMET / SIGMET overlay chart spec derivation.
 *
 * Take the AirmetAdvisory[] from layer-2 derivation and emit the
 * advisory-overlay chart's source JSON + spec.yaml.
 */

import type { AirmetAdvisory } from '../products/airmet';
import type { TruthModel } from '../truth/types';
import type { ChartArtifact } from './types';

export function deriveAirmetChart(truth: TruthModel, airmets: AirmetAdvisory[], scenarioId: string): ChartArtifact {
	const slug = `wx-scenario-${scenarioId}-airmet-sigmet`;

	const sourceJson = {
		issued: truth.validAt,
		valid_until: airmets[0]?.validTo ?? truth.validAt,
		_source: 'Generated by spike-01 wx-engine from truth.hazardZones.',
		advisories: airmets.map((a) => ({
			id: a.id,
			kind: a.kind,
			label: a.label,
			labelLonLat: a.labelLonLat,
			rings: a.rings,
		})),
	};

	const spec = {
		slug,
		type: 'advisory-overlay',
		title: 'AIRMETs (truth-derived)',
		subtitle: `Issued ${truth.validAt} -- composes with the same-time surface analysis`,
		projection: { kind: 'lambert', parallels: [33, 45] as [number, number], rotate: [-96, -39] as [number, number] },
		extent: 'conus',
		sources: {
			advisories: `cache://scenarios/${scenarioId}/airmet-overlay.json`,
		},
		options: {
			show_legend: true,
			show_labels: true,
			source_attribution: 'Spike 01 wx-engine -- truth-derived synthetic AIRMETs',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				cacheRelPath: `scenarios/${scenarioId}/airmet-overlay.json`,
				content: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}
