/**
 * Spike 01 -- Layer 3 prog chart spec derivation.
 *
 * Advance the truth model 12 hours forward, derive forecast positions
 * for centers + fronts, and emit forecast hazard polygons (turbulence /
 * icing / IFR) projected forward as well.
 */

import { advanceTruth, type TruthModel } from '../truth/types';
import type { ChartArtifact } from './types';

export function deriveProgChart(truth: TruthModel, leadHours: number, scenarioId: string): ChartArtifact {
	const slug = `wx-scenario-${scenarioId}-prog-${leadHours}hr`;
	const projected = advanceTruth(truth, leadHours);

	const centers = projected.synoptic.pressureSystems.map((s) => ({
		kind: s.kind,
		lon: s.lon,
		lat: s.lat,
		pressureMb: s.centralPressureMb,
	}));
	const fronts = projected.synoptic.fronts.map((f) => ({
		kind: f.kind,
		points: f.points,
		pipSide: f.pipSide,
	}));

	// Hazard polygons: forecast IFR / turb / icing zones.
	const hazards = projected.hazardZones.map((hz, i) => {
		// Close ring.
		const ring = [...hz.polygon];
		const first = ring[0];
		const last = ring[ring.length - 1];
		if (first !== undefined && last !== undefined && (first[0] !== last[0] || first[1] !== last[1])) {
			ring.push(first);
		}
		const centroid = polygonCentroid(hz.polygon);
		const kind: 'turbulence' | 'icing' | 'ifr' = hz.kind === 'mountain-obscuration' ? 'ifr' : (hz.kind as 'turbulence' | 'icing' | 'ifr');
		return {
			id: `${hz.id}-${leadHours}h`,
			kind,
			label: `${kind.toUpperCase()} forecast +${leadHours}h`,
			labelLonLat: centroid,
			rings: [ring],
		};
	});

	const sourceJson = {
		title: `${leadHours}hr prog VALID ${projected.validAt} -- truth-evolved from ${truth.validAt}`,
		validTimeIso: projected.validAt,
		forecastHours: leadHours,
		_source: 'Generated by spike-01 wx-engine via truth-state advance.',
		centers,
		fronts,
		hazards,
	};

	const spec = {
		slug,
		type: 'prog-chart',
		title: `${leadHours}hr Prog (truth-derived)`,
		subtitle: `Forecast valid ${projected.validAt} -- evolved from ${truth.validAt}`,
		projection: { kind: 'lambert', parallels: [33, 45] as [number, number], rotate: [-96, -39] as [number, number] },
		extent: 'conus',
		sources: {
			forecast: `cache://scenarios/${scenarioId}/prog-${leadHours}hr.json`,
		},
		options: {
			isobar_interval_mb: 4,
			emphasize_every_mb: 8,
			show_h_l_markers: true,
			show_hazards: true,
			show_legend: true,
			source_attribution: 'Spike 01 wx-engine -- truth-derived synthetic forecast',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				cacheRelPath: `scenarios/${scenarioId}/prog-${leadHours}hr.json`,
				content: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}

function polygonCentroid(poly: [number, number][]): [number, number] {
	let sx = 0;
	let sy = 0;
	for (const p of poly) {
		sx += p[0];
		sy += p[1];
	}
	const n = poly.length || 1;
	return [sx / n, sy / n];
}
