/**
 * Spike 01 -- Layer 3 surface-analysis chart spec derivation.
 *
 * Build the wx-charts surface-analysis spec.yaml + the JSON source file
 * it references. Source-data shape (per libs/wx-charts/src/charts/
 * surface-analysis.ts surfaceAnalysisSourceSchema):
 *   { centers, fronts, stations? }
 *
 * Centers come from truth.synoptic.pressureSystems; fronts from
 * truth.synoptic.fronts; stations from a sparse overlay of the route +
 * reference stations with conditions sampled from each METAR.
 */

import type { TruthModel } from '../truth/types';
import type { DerivedMetar } from '../products/metar';
import type { ChartArtifact } from './types';

export function deriveSurfaceAnalysisChart(
	truth: TruthModel,
	metars: DerivedMetar[],
	scenarioId: string,
): ChartArtifact {
	const slug = `wx-scenario-${scenarioId}-surface-analysis`;

	const centers = truth.synoptic.pressureSystems.map((s) => ({
		kind: s.kind,
		lon: s.lon,
		lat: s.lat,
		pressureMb: s.centralPressureMb,
	}));

	const fronts = truth.synoptic.fronts.map((f) => ({
		kind: f.kind,
		points: f.points,
		pipSide: f.pipSide,
	}));

	const stations = metars.map((m) => {
		const cToF = (c: number | null): number | undefined =>
			c === null ? undefined : Math.round((c * 9) / 5 + 32);
		const skyCover =
			m.parsed.clouds.length === 0
				? 'CLR'
				: (m.parsed.clouds[0]?.cover === 'SKC'
					? 'CLR'
					: m.parsed.clouds[0]?.cover ?? 'CLR');
		// Drop VV if present (the surface-analysis station-model schema does not allow VV).
		const safeSkyCover: 'CLR' | 'FEW' | 'SCT' | 'BKN' | 'OVC' =
			skyCover === 'FEW' || skyCover === 'SCT' || skyCover === 'BKN' || skyCover === 'OVC' ? skyCover : 'CLR';
		return {
			id: m.parsed.station,
			lon: m.stationLon,
			lat: m.stationLat,
			tempF: cToF(m.parsed.tempC),
			dewF: cToF(m.parsed.dewpointC),
			pressureMb: m.parsed.altimeterInHg !== null ? Math.round(m.parsed.altimeterInHg * 33.8639) : undefined,
			windDir: m.parsed.wind?.directionDeg ?? null,
			windKt: m.parsed.wind?.speedKt ?? null,
			skyCover: safeSkyCover,
		};
	});

	const sourceJson = {
		title: `Truth-derived surface analysis for ${scenarioId}`,
		validTimeIso: truth.validAt,
		_source: 'Generated by spike-01 wx-engine from truth model.',
		_pattern_summary: truth.narrative,
		centers,
		fronts,
		stations,
	};

	const spec = {
		slug,
		type: 'surface-analysis',
		title: 'Surface Analysis (truth-derived)',
		subtitle: `${truth.validAt} -- ${truth.narrative.slice(0, 80)}`,
		projection: { kind: 'lambert', parallels: [33, 45] as [number, number], rotate: [-96, -39] as [number, number] },
		extent: 'conus',
		sources: {
			fronts: `cache://scenarios/${scenarioId}/surface-analysis.json`,
		},
		options: {
			station_density: 'hubs',
			isobar_interval_mb: 4,
			emphasize_every_mb: 8,
			show_h_l_markers: true,
			source_attribution: 'Spike 01 wx-engine -- truth-derived synthetic',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				cacheRelPath: `scenarios/${scenarioId}/surface-analysis.json`,
				content: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}
