/**
 * Layer-3 advisory-overlay chart spec derivation.
 *
 * Composites the layer-2 AIRMET output as a polygon overlay against the
 * CONUS basemap. Maps `AirmetAdvisory` records directly to the wx-charts
 * advisory-overlay source-data shape (`advisories: [{ id, kind, label,
 * labelLonLat, rings }]`). The wx-charts library renders the spec via
 * `renderAirmetSigmet`; the schema is `airmetSigmetSpecSchema` and the
 * spec `type` is `advisory-overlay`.
 *
 * Slug preserves the spike's chart-kind suffix (`airmet-sigmet`) under the
 * ADR 027 PR 3 family path. The chart-spec mirror at
 * `data/charts/wx/wx-scenarios/frontal-xc-march/airmet-sigmet/` is the
 * regression baseline. Future scenarios mirror the same suffix.
 *
 * Lifted from the spike's pre-retirement
 * `spikes/wx-engine/src/charts/airmet-overlay.ts` (PR #801 -- now retired).
 */

import { wxScenarioChartSlug } from '@ab/constants';
import type { AirmetAdvisory } from '../products/types';
import type { TruthModel } from '../truth/types';
import type { ChartArtifact } from './types';

export function deriveAdvisoryOverlayChart(
	truth: TruthModel,
	airmets: AirmetAdvisory[],
	scenarioId: string,
): ChartArtifact {
	const slug = wxScenarioChartSlug(scenarioId, 'airmet-sigmet');
	const cacheRelPath = `scenarios/${scenarioId}/airmet-overlay.json`;

	const sourceJson = {
		issued: truth.validAt,
		valid_until: airmets[0]?.validTo ?? truth.validAt,
		_source: 'Generated by wx-engine from truth.hazardZones.',
		advisories: airmets.map((a) => ({
			id: a.id,
			kind: a.kind,
			label: a.label,
			labelLonLat: a.labelLonLat,
			rings: a.rings,
		})),
	};

	const spec = {
		slug,
		type: 'advisory-overlay' as const,
		title: 'AIRMETs (truth-derived)',
		subtitle: `Issued ${truth.validAt} -- composes with the same-time surface analysis`,
		projection: {
			kind: 'lambert' as const,
			parallels: [33, 45] as [number, number],
			rotate: [-96, -39] as [number, number],
		},
		extent: 'conus' as const,
		sources: {
			advisories: `cache://${cacheRelPath}`,
		},
		options: {
			show_legend: true,
			show_labels: true,
			source_attribution: 'wx-engine -- truth-derived synthetic AIRMETs',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				path: cacheRelPath,
				bytes: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}
