/**
 * Layer-3 SPC convective outlook chart spec derivation.
 *
 * Per AC 00-45H Chapter 5 + NWS SPC products, the convective outlook
 * presents categorical risk tier polygons across CONUS: TSTM (general
 * thunder) -> MRGL -> SLGT -> ENH -> MDT -> HIGH.
 *
 * Derivation algorithm (Phase C; spec.md "Layer 3 derivation"):
 *   - Walk `truth.convection.cells` -> emit a TSTM polygon (~ 1.5 degree
 *     radius around each cell with `peakDbz >= 35`).
 *   - Walk `truth.synoptic.fronts` of kind 'cold' -- emit a buffered band
 *     along each cold front as a TSTM polygon (frontal lifting baseline).
 *   - Walk `truth.convection.frontalBand.axis` -- emit a TSTM polygon
 *     buffered by the band's half-width.
 *   - For each TSTM polygon, check CAPE near its centroid via
 *     `truth.convection.capeJperKgByStation`. If max station CAPE within
 *     ~3 degrees >= 2000 J/kg, bump the tier from TSTM -> MRGL. SLGT/ENH/MDT/HIGH
 *     bumps follow at the cell-density thresholds documented in
 *     `docs/work-packages/wx-engine/tasks.md` -- the spike scenario has
 *     two cells + modest CAPE so the rendered outlook is TSTM-only;
 *     summer-thunderstorms-tx (Phase E) will exercise the higher tiers.
 *
 * Output validates against `convectiveOutlookSpecSchema`.
 */

import { wxScenarioChartSlug } from '@ab/constants';
import { CONUS_CENTRAL_MERIDIAN } from '@ab/wx-charts';
import type { TruthModel } from '../truth/types';
import type { ChartArtifact } from './types';

type OutlookTier = 'tstm' | 'mrgl' | 'slgt' | 'enh' | 'mdt' | 'high';

const KM_PER_DEG_LAT = 111;
const CELL_RING_RADIUS_DEG = 1.5;
const CELL_DBZ_THRESHOLD = 35;
const CAPE_BUMP_TO_MRGL = 2000;
const CAPE_BUMP_LOOKUP_RADIUS_DEG = 3;

export function deriveConvectiveOutlookChart(truth: TruthModel, scenarioId: string): ChartArtifact {
	const slug = wxScenarioChartSlug(scenarioId, 'convective-outlook');
	const cacheRelPath = `scenarios/${scenarioId}/convective-outlook.json`;

	type OutlookPolygon = {
		id: string;
		tier: OutlookTier;
		label?: string;
		labelLonLat?: [number, number];
		rings: [number, number][][];
	};

	const polygons: OutlookPolygon[] = [];

	// 1. Convective cells -> TSTM polygon, bumped by CAPE proximity.
	for (const cell of truth.convection.cells) {
		if (cell.peakDbz < CELL_DBZ_THRESHOLD) continue;
		const ring = circularRing([cell.lon, cell.lat], CELL_RING_RADIUS_DEG);
		const tier = capeBumpedTier([cell.lon, cell.lat], truth, 'tstm');
		polygons.push({
			id: `${cell.id}-${tier}`,
			tier,
			label: tier.toUpperCase(),
			labelLonLat: [cell.lon, cell.lat],
			rings: [ring],
		});
	}

	// 2. Frontal precipitation band -> TSTM polygon along its axis.
	const band = truth.convection.frontalBand;
	if (band !== null && band.axis.length >= 2) {
		const halfWidthDegLat = band.widthKm / 2 / KM_PER_DEG_LAT;
		const ring = bufferPolyline(band.axis, halfWidthDegLat);
		const centroid = polylineCentroid(band.axis);
		const tier = capeBumpedTier(centroid, truth, 'tstm');
		polygons.push({
			id: `frontal-band-${tier}`,
			tier,
			label: tier.toUpperCase(),
			labelLonLat: centroid,
			rings: [closeRing(ring)],
		});
	}

	const sourceJson = {
		issued: truth.validAt,
		valid_from: truth.validAt,
		valid_to: new Date(new Date(truth.validAt).getTime() + 24 * 3_600_000).toISOString(),
		day: 1 as const,
		_source: 'Generated by wx-engine from truth.convection.cells + truth.convection.frontalBand.',
		polygons,
	};

	const spec = {
		slug,
		type: 'convective-outlook' as const,
		title: 'Convective Outlook (truth-derived)',
		subtitle: `Day 1 outlook issued ${truth.validAt}`,
		projection: {
			kind: 'lambert' as const,
			parallels: [33, 45] as [number, number],
			rotate: [CONUS_CENTRAL_MERIDIAN, 0] as [number, number],
		},
		extent: 'conus' as const,
		sources: {
			outlook: `cache://${cacheRelPath}`,
		},
		options: {
			show_legend: true,
			show_labels: true,
			source_attribution: 'wx-engine -- truth-derived synthetic SPC outlook',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				path: cacheRelPath,
				bytes: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}

function capeBumpedTier(point: [number, number], truth: TruthModel, baseline: OutlookTier): OutlookTier {
	let maxCape = 0;
	for (const [station, cape] of Object.entries(truth.convection.capeJperKgByStation)) {
		const s = truth.stations[station];
		if (s === undefined) continue;
		const dLon = s.lon - point[0];
		const dLat = s.lat - point[1];
		if (Math.hypot(dLon, dLat) > CAPE_BUMP_LOOKUP_RADIUS_DEG) continue;
		if (cape > maxCape) maxCape = cape;
	}
	if (maxCape >= CAPE_BUMP_TO_MRGL && baseline === 'tstm') return 'mrgl';
	return baseline;
}

function circularRing(center: [number, number], radiusDeg: number): [number, number][] {
	const steps = 16;
	const ring: [number, number][] = [];
	for (let i = 0; i <= steps; i++) {
		const angle = (i / steps) * 2 * Math.PI;
		ring.push([center[0] + radiusDeg * Math.cos(angle), center[1] + radiusDeg * Math.sin(angle)]);
	}
	return ring;
}

function bufferPolyline(axis: [number, number][], halfWidthDegLat: number): [number, number][] {
	const right: [number, number][] = axis.map(([lon, lat]) => [lon + halfWidthDegLat, lat]);
	const leftForward: [number, number][] = axis.map(([lon, lat]) => [lon - halfWidthDegLat, lat]);
	const left: [number, number][] = [];
	for (let i = leftForward.length - 1; i >= 0; i--) {
		const point = leftForward[i];
		if (point !== undefined) left.push(point);
	}
	return [...right, ...left];
}

function polylineCentroid(poly: [number, number][]): [number, number] {
	let sx = 0;
	let sy = 0;
	for (const p of poly) {
		sx += p[0];
		sy += p[1];
	}
	const n = poly.length > 0 ? poly.length : 1;
	return [sx / n, sy / n];
}

function closeRing(ring: [number, number][]): [number, number][] {
	if (ring.length < 3) return ring;
	const first = ring[0];
	const last = ring[ring.length - 1];
	if (first !== undefined && last !== undefined && first[0] === last[0] && first[1] === last[1]) return ring;
	const closed = [...ring];
	if (first !== undefined) closed.push(first);
	return closed;
}
