/**
 * Layer-3 freezing-level forecast chart spec derivation.
 *
 * Per AC 00-45H Chapter 5 and AC 00-6B Chapter 17, the freezing-level
 * forecast publishes the height of the lowest 0 degC isotherm in ft MSL
 * on a regular grid across CONUS. The wx-charts library's freezing-level
 * renderer accepts either
 *
 *   - a pre-computed `altitude_grid` (regular gridded scalar field), or
 *   - a `synth` block (sum-of-Gaussians on a tilted-latitude plane) that
 *     the renderer expands into the grid at render time.
 *
 * The truth model carries `upperLevel.windByAltitude[*].meanTempC` -- a
 * 1-D temperature profile vs altitude. We interpolate that profile to
 * find the altitude (ft MSL) where mean temp = 0 degC. That altitude is
 * the scenario's "background" freezing level. The tilted-plane synth
 * parameters lower this background by 1500 ft over a northern band and
 * raise it by 1500 ft over a southern band, mirroring the AC 00-6B
 * latitudinal tilt. Hazard-zone polygons of kind 'icing' contribute
 * negative-amplitude Gaussian bumps (cold pools) that depress the
 * freezing level locally so the rendered chart matches the icing AIRMET
 * geometry.
 */

import { wxScenarioChartSlug } from '@ab/constants';
import type { TruthModel } from '../truth/types';
import type { ChartArtifact } from './types';
import { CONUS_CENTRAL_MERIDIAN } from '@ab/wx-charts';

const DEFAULT_TILT_HALF_RANGE_FT = 1500;
const ICING_HAZARD_AMPLITUDE_FT = -2500;
const ICING_HAZARD_SIGMA_DEG = 4;
const FREEZING_LEVEL_DEFAULT_FT = 8000;

export function deriveFreezingLevelChart(truth: TruthModel, scenarioId: string): ChartArtifact {
	const slug = wxScenarioChartSlug(scenarioId, 'freezing-level');
	const cacheRelPath = `scenarios/${scenarioId}/freezing-level.json`;

	// 1. Compute the scenario's background freezing level via 1-D linear
	// interpolation of `meanTempC` vs `altitudeFt`.
	const backgroundFt = interpolateFreezingLevelFt(truth);

	// 2. Tilt: northern (cold) latitudes lower; southern (warm) higher.
	const northFloorFt = Math.max(0, Math.round(backgroundFt - DEFAULT_TILT_HALF_RANGE_FT));
	const southCeilingFt = Math.round(backgroundFt + DEFAULT_TILT_HALF_RANGE_FT);

	// 3. Bumps from icing hazard zones (negative amplitude depresses the
	// freezing level locally so the rendered chart shows lower altitudes
	// over the iced region).
	const bumps = truth.hazardZones
		.filter((hz) => hz.kind === 'icing')
		.map((hz) => {
			const centroid = polygonCentroid(hz.polygon);
			return {
				lon: centroid[0],
				lat: centroid[1],
				amplitude_ft: ICING_HAZARD_AMPLITUDE_FT,
				sigma: ICING_HAZARD_SIGMA_DEG,
			};
		});

	const sourceJson = {
		issued: truth.validAt,
		valid_at: truth.validAt,
		_source: 'Generated by wx-engine from truth.upperLevel.windByAltitude + truth.hazardZones.',
		synth: {
			north_floor_ft: northFloorFt,
			south_ceiling_ft: southCeilingFt,
			tilt_deg: 12,
			bumps,
		},
	};

	const spec = {
		slug,
		type: 'freezing-level' as const,
		title: 'Freezing Level Forecast (truth-derived)',
		subtitle: `Valid ${truth.validAt} -- background 0 deg C at ${backgroundFt} ft MSL`,
		projection: {
			kind: 'lambert' as const,
			parallels: [33, 45] as [number, number],
			rotate: [CONUS_CENTRAL_MERIDIAN, 0] as [number, number],
		},
		extent: 'conus' as const,
		sources: {
			field: `cache://${cacheRelPath}`,
		},
		options: {
			show_legend: true,
			show_contours: true,
			contour_interval_ft: 2000,
			source_attribution: 'wx-engine -- truth-derived synthetic',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				path: cacheRelPath,
				bytes: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}

function interpolateFreezingLevelFt(truth: TruthModel): number {
	const rows = [...truth.upperLevel.windByAltitude].sort((a, b) => a.altitudeFt - b.altitudeFt);
	if (rows.length === 0) return FREEZING_LEVEL_DEFAULT_FT;

	const first = rows[0];
	const last = rows[rows.length - 1];
	if (first === undefined || last === undefined) return FREEZING_LEVEL_DEFAULT_FT;
	if (first.meanTempC <= 0) return first.altitudeFt;
	if (last.meanTempC >= 0) return last.altitudeFt;

	for (let i = 0; i < rows.length - 1; i++) {
		const a = rows[i];
		const b = rows[i + 1];
		if (a === undefined || b === undefined) continue;
		if (a.meanTempC > 0 && b.meanTempC <= 0) {
			// Linear interpolation: temp(altitude) crosses zero somewhere
			// between a and b.
			const fraction = a.meanTempC / (a.meanTempC - b.meanTempC);
			return Math.round(a.altitudeFt + fraction * (b.altitudeFt - a.altitudeFt));
		}
	}
	return FREEZING_LEVEL_DEFAULT_FT;
}

function polygonCentroid(poly: [number, number][]): [number, number] {
	let sx = 0;
	let sy = 0;
	for (const p of poly) {
		sx += p[0];
		sy += p[1];
	}
	const n = poly.length > 0 ? poly.length : 1;
	return [sx / n, sy / n];
}
