/**
 * Layer-3 G-AIRMET icing chart spec derivation.
 *
 * The G-AIRMET icing product evolved from the legacy AIRMET Zulu by
 * partitioning the forecast into discrete severity polygons. This
 * derivation filters the truth-aware engine's AIRMET output to the
 * `airmet-zulu` family and lifts each ring into a G-AIRMET icing area
 * with the canonical intensity / altitude-band metadata.
 *
 * The wx-charts icing-gairmet renderer requires per-area `intensity` and
 * `altLow` / `altHigh` (ft MSL). We pull the altitude band from the
 * AIRMET's source hazard zone via `truth.hazardZones` lookup so the
 * G-AIRMET polygon altitude band matches the AIRMET text-product
 * altitude exactly (killer-feature consistency).
 */

import { AIRMET_FAMILIES } from '@ab/constants';
import type { TruthModel } from '../truth/types';
import type { AirmetAdvisory } from '../products/types';
import type { ChartArtifact } from './types';

type IcingIntensity = 'icing-light' | 'icing-light-mod' | 'icing-moderate' | 'icing-severe';
type IcingType = 'rime' | 'clear' | 'mixed' | 'unspecified';

const SEVERITY_TO_INTENSITY: Record<string, IcingIntensity> = {
	light: 'icing-light',
	moderate: 'icing-moderate',
	severe: 'icing-severe',
};

const ALTITUDE_FALLBACK_LOW_FT = 2000;
const ALTITUDE_FALLBACK_HIGH_FT = 16000;

export function deriveGAirmetIcingChart(
	truth: TruthModel,
	airmets: AirmetAdvisory[],
	scenarioId: string,
): ChartArtifact {
	const slug = `wx-scenario-${scenarioId}-g-airmet-icing`;
	const cacheRelPath = `scenarios/${scenarioId}/g-airmet-icing.json`;

	const areas = airmets
		.filter((a) => a.kind === AIRMET_FAMILIES.ZULU)
		.map((a) => {
			const hazard = truth.hazardZones.find((hz) => hz.id === a.fromHazardZoneId);
			const altLow = hazard?.altitudeBandFtMsl.min ?? ALTITUDE_FALLBACK_LOW_FT;
			const altHighRaw = hazard?.altitudeBandFtMsl.max;
			const altHigh = altHighRaw === null || altHighRaw === undefined ? ALTITUDE_FALLBACK_HIGH_FT : altHighRaw;
			const intensity: IcingIntensity =
				hazard !== undefined ? (SEVERITY_TO_INTENSITY[hazard.severity] ?? 'icing-moderate') : 'icing-moderate';
			const icingType: IcingType = 'mixed';
			const altBandLabel = formatAltBand(altLow, altHigh);
			return {
				id: `${a.id}-gairmet`,
				intensity,
				type: icingType,
				altLow,
				altHigh,
				label: `${labelForIntensity(intensity)}\n${altBandLabel}`,
				labelLonLat: a.labelLonLat,
				rings: a.rings,
			};
		});

	const validToIso = airmets[0]?.validTo ?? truth.validAt;
	const sourceJson = {
		issued: truth.validAt,
		valid_from: truth.validAt,
		valid_to: validToIso,
		_source: 'Generated by wx-engine from AIRMET Zulu family + truth.hazardZones.',
		areas,
	};

	const spec = {
		slug,
		type: 'icing-gairmet' as const,
		title: 'G-AIRMET Icing (truth-derived)',
		subtitle: `Issued ${truth.validAt} -- Zulu family only`,
		projection: {
			kind: 'lambert' as const,
			parallels: [33, 45] as [number, number],
			rotate: [-96, -39] as [number, number],
		},
		extent: 'conus' as const,
		sources: {
			areas: `cache://${cacheRelPath}`,
		},
		options: {
			show_legend: true,
			show_labels: true,
			source_attribution: 'wx-engine -- truth-derived synthetic G-AIRMET icing',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				path: cacheRelPath,
				bytes: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}

function labelForIntensity(intensity: IcingIntensity): string {
	switch (intensity) {
		case 'icing-light':
			return 'LGT ICE';
		case 'icing-light-mod':
			return 'LGT-MOD ICE';
		case 'icing-moderate':
			return 'MOD ICE';
		case 'icing-severe':
			return 'SEV ICE';
	}
}

function formatAltBand(low: number, high: number): string {
	const fmt = (ft: number) => (ft < 1500 ? 'SFC' : `${Math.round(ft / 100)}`);
	return `${fmt(low)}-${fmt(high)}`;
}
