/**
 * Layer-3 G-AIRMET turbulence chart spec derivation.
 *
 * Filters the truth-aware engine's AIRMET output to the `airmet-tango`
 * family and lifts each ring into a G-AIRMET turbulence area with the
 * canonical severity / flight-level band metadata.
 *
 * The wx-charts turbulence-gairmet renderer requires `severity`, `topFl`
 * and `bottomFl` (flight levels: FL080 = 80, FL240 = 240, surface = 0).
 * The truth model's `HazardZone.altitudeBandFtMsl` is in feet MSL; we
 * round to the nearest flight-level value (ft / 100) for the rendered
 * polygon label. When `max === null` the polygon is "AND ABOVE" -- we
 * cap it at FL450 to match the wx-charts schema's flight-level integer
 * constraint.
 */

import { AIRMET_FAMILIES } from '@ab/constants';
import type { TruthModel } from '../truth/types';
import type { AirmetAdvisory } from '../products/types';
import type { ChartArtifact } from './types';

type TurbSeverity = 'light' | 'moderate' | 'severe';

const SEVERITY_MAP: Record<string, TurbSeverity> = {
	light: 'light',
	moderate: 'moderate',
	severe: 'severe',
};

const TOP_FL_FALLBACK = 240;
const BOTTOM_FL_FALLBACK = 0;
const TOP_FL_CAP = 450;

export function deriveGAirmetTurbulenceChart(
	truth: TruthModel,
	airmets: AirmetAdvisory[],
	scenarioId: string,
): ChartArtifact {
	const slug = `wx-scenario-${scenarioId}-g-airmet-turbulence`;
	const cacheRelPath = `scenarios/${scenarioId}/g-airmet-turbulence.json`;

	const areas = airmets
		.filter((a) => a.kind === AIRMET_FAMILIES.TANGO)
		.map((a) => {
			const hazard = truth.hazardZones.find((hz) => hz.id === a.fromHazardZoneId);
			const bottomFl = hazard !== undefined ? feetMslToFlightLevel(hazard.altitudeBandFtMsl.min) : BOTTOM_FL_FALLBACK;
			const topFl =
				hazard !== undefined
					? hazard.altitudeBandFtMsl.max === null
						? TOP_FL_CAP
						: feetMslToFlightLevel(hazard.altitudeBandFtMsl.max)
					: TOP_FL_FALLBACK;
			const severity: TurbSeverity = hazard !== undefined ? (SEVERITY_MAP[hazard.severity] ?? 'moderate') : 'moderate';
			const label = `${labelForSeverity(severity)}\n${formatFlBand(bottomFl, topFl)}`;
			return {
				id: `${a.id}-gairmet`,
				severity,
				topFl,
				bottomFl,
				label,
				labelLonLat: a.labelLonLat,
				rings: a.rings,
			};
		});

	const validIso = airmets[0]?.validTo ?? truth.validAt;
	const sourceJson = {
		issued: truth.validAt,
		valid: `${truth.validAt}/${validIso}`,
		_source: 'Generated by wx-engine from AIRMET Tango family + truth.hazardZones.',
		areas,
	};

	const spec = {
		slug,
		type: 'turbulence-gairmet' as const,
		title: 'G-AIRMET Turbulence (truth-derived)',
		subtitle: `Issued ${truth.validAt} -- Tango family only`,
		projection: {
			kind: 'lambert' as const,
			parallels: [33, 45] as [number, number],
			rotate: [-96, -39] as [number, number],
		},
		extent: 'conus' as const,
		sources: {
			areas: `cache://${cacheRelPath}`,
		},
		options: {
			show_legend: true,
			show_labels: true,
			source_attribution: 'wx-engine -- truth-derived synthetic G-AIRMET turbulence',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				path: cacheRelPath,
				bytes: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}

function feetMslToFlightLevel(ft: number): number {
	if (ft <= 0) return 0;
	return Math.round(ft / 100);
}

function labelForSeverity(severity: TurbSeverity): string {
	switch (severity) {
		case 'light':
			return 'LGT TURB';
		case 'moderate':
			return 'MOD TURB';
		case 'severe':
			return 'SEV TURB';
	}
}

function formatFlBand(bottomFl: number, topFl: number): string {
	const fmt = (fl: number) => (fl === 0 ? 'SFC' : `FL${String(fl).padStart(3, '0')}`);
	return `${fmt(bottomFl)}-${fmt(topFl)}`;
}
