/**
 * Layer-3 GFA (Graphical Forecasts for Aviation) chart spec derivation.
 *
 * Per AC 00-45H Chapter 5, the GFA is the AWC's CONUS-wide graphical
 * forecast product that replaces the legacy Area Forecast text product.
 * It overlays cloud-cover / precipitation / IFR / MVFR polygons on a CONUS
 * basemap, partitioned into the SFC-180 (low-altitude) and 180-450 (jet)
 * altitude bands. The wx-charts library renders the polygon overlay
 * via `renderGfa` against the `gfaSpecSchema` contract.
 *
 * Derivation algorithm:
 *   - AIRMET IFR (Sierra family) polygons -> `ifr_area`
 *   - AIRMET turbulence (Tango family) -- treated as cloud cover proxy
 *     when the polygon overlaps the same region. Tango carries no cloud
 *     metadata in the truth model; we DO NOT synthesize cloud polygons
 *     from Tango. Instead we fall back to the truth model's airMasses to
 *     synthesize a `clouds_bkn_ovc` polygon per air mass with
 *     `meanCloudCover === 'BKN'` or `'OVC'`.
 *   - Convective frontal-band axis (when present) -> `precip_tstm`
 *     polygon (band buffered to half-width on each side).
 *   - Per-TAF flight category dots are NOT in the gfa-spec schema (the
 *     renderer draws polygons only). Phase D's commentary cites the
 *     per-station TAFs separately.
 *
 * Polygon ids are deterministic so spec.yaml round-trips byte-stable.
 */

import { AIRMET_FAMILIES, wxScenarioChartSlug } from '@ab/constants';
import type { AirmetAdvisory, DerivedTaf } from '../products/types';
import type { AirMass, TruthModel } from '../truth/types';
import type { ChartArtifact } from './types';
import { CONUS_CENTRAL_MERIDIAN } from '@ab/wx-charts';

const KM_PER_DEG_LAT = 111;

export function deriveGfaChart(
	truth: TruthModel,
	airmets: AirmetAdvisory[],
	_tafs: DerivedTaf[],
	scenarioId: string,
): ChartArtifact {
	const slug = wxScenarioChartSlug(scenarioId, 'gfa');
	const cacheRelPath = `scenarios/${scenarioId}/gfa.json`;

	type GfaPolygon = {
		id: string;
		kind:
			| 'clouds_few_sct'
			| 'clouds_bkn_ovc'
			| 'precip_rain'
			| 'precip_snow'
			| 'precip_mixed'
			| 'precip_tstm'
			| 'ifr_area'
			| 'mvfr_area';
		label?: string;
		labelLonLat?: [number, number];
		rings: [number, number][][];
	};

	const polygons: GfaPolygon[] = [];

	// 1. IFR / MVFR areas from Sierra-family AIRMETs.
	for (const a of airmets) {
		if (a.kind !== AIRMET_FAMILIES.SIERRA) continue;
		polygons.push({
			id: `${a.id}-ifr`,
			kind: 'ifr_area',
			label: 'IFR',
			labelLonLat: a.labelLonLat,
			rings: a.rings,
		});
	}

	// 2. Cloud polygons from air-mass mean cloud cover (BKN/OVC -> bkn_ovc; FEW/SCT -> few_sct).
	for (const am of truth.airMasses) {
		const kind: GfaPolygon['kind'] | null = airMassCloudKind(am);
		if (kind === null) continue;
		polygons.push({
			id: `${am.id}-clouds`,
			kind,
			label: `${am.meanCloudCover}`,
			labelLonLat: polygonCentroid(am.polygon),
			rings: [closeRing(am.polygon)],
		});
	}

	// 3. Convective frontal band -> precip_tstm polygon (axis buffered by widthKm/2).
	const band = truth.convection.frontalBand;
	if (band !== null && band.axis.length >= 2) {
		const halfWidthDegLat = band.widthKm / 2 / KM_PER_DEG_LAT;
		const polygon = bufferPolyline(band.axis, halfWidthDegLat);
		polygons.push({
			id: 'frontal-band-tstm',
			kind: 'precip_tstm',
			label: 'TSRA',
			labelLonLat: polylineCentroid(band.axis),
			rings: [closeRing(polygon)],
		});
	}

	const sourceJson = {
		issued: truth.validAt,
		valid_at: truth.validAt,
		altitude_band: 'SFC-180' as const,
		_source: 'Generated by wx-engine from truth.hazardZones + truth.airMasses + truth.convection.',
		polygons,
	};

	const spec = {
		slug,
		type: 'gfa' as const,
		title: 'Graphical Forecasts for Aviation (truth-derived)',
		subtitle: `Issued ${truth.validAt} -- SFC-180 band`,
		projection: {
			kind: 'lambert' as const,
			parallels: [33, 45] as [number, number],
			rotate: [CONUS_CENTRAL_MERIDIAN, 0] as [number, number],
		},
		extent: 'conus' as const,
		sources: {
			polygons: `cache://${cacheRelPath}`,
		},
		options: {
			show_legend: true,
			show_labels: true,
			source_attribution: 'wx-engine -- truth-derived synthetic GFA',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				path: cacheRelPath,
				bytes: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}

function airMassCloudKind(am: AirMass): 'clouds_few_sct' | 'clouds_bkn_ovc' | null {
	switch (am.meanCloudCover) {
		case 'BKN':
		case 'OVC':
			return 'clouds_bkn_ovc';
		case 'FEW':
		case 'SCT':
			return 'clouds_few_sct';
		default:
			return null;
	}
}

function polygonCentroid(poly: [number, number][]): [number, number] {
	let sx = 0;
	let sy = 0;
	for (const p of poly) {
		sx += p[0];
		sy += p[1];
	}
	const n = poly.length > 0 ? poly.length : 1;
	return [sx / n, sy / n];
}

function polylineCentroid(poly: [number, number][]): [number, number] {
	return polygonCentroid(poly);
}

function closeRing(ring: [number, number][]): [number, number][] {
	if (ring.length < 3) return ring;
	const first = ring[0];
	const last = ring[ring.length - 1];
	if (first !== undefined && last !== undefined && first[0] === last[0] && first[1] === last[1]) return ring;
	const closed = [...ring];
	if (first !== undefined) closed.push(first);
	return closed;
}

/**
 * Buffer a polyline into a closed polygon by offsetting each point in
 * latitude by `halfWidthDegLat`. Simple north/south buffer -- adequate for
 * a tilted frontal band where the axis is roughly N-S oriented. For an
 * E-W band we'd buffer in longitude instead; for v1 we approximate with
 * lat-only buffer (the spike's hand-coded frontal axes are all N-S
 * oriented).
 */
function bufferPolyline(axis: [number, number][], halfWidthDegLat: number): [number, number][] {
	const right: [number, number][] = axis.map(([lon, lat]) => [lon + halfWidthDegLat, lat]);
	const leftForward: [number, number][] = axis.map(([lon, lat]) => [lon - halfWidthDegLat, lat]);
	const left: [number, number][] = [];
	for (let i = leftForward.length - 1; i >= 0; i--) {
		const point = leftForward[i];
		if (point !== undefined) left.push(point);
	}
	return [...right, ...left];
}
