/**
 * Layer-3 prog-chart spec derivation (forecast surface analysis).
 *
 * The Prog chart is the forecast counterpart to the surface analysis. Per
 * AC 00-45H Chapter 5, the WPC issues 12 / 24 / 36 / 48-hour Surface
 * Prognostic Charts showing forecast positions of pressure systems,
 * fronts, and hazard polygons (IFR / turbulence / icing). This derivation
 * advances the truth model `leadHours` forward via `advanceTruth`, then
 * formats the projected synoptic state plus hazard polygons into the
 * wx-charts `prog-chart` spec.
 *
 * Lifted from the spike's pre-retirement
 * `spikes/wx-engine/src/charts/prog-chart.ts` (PR #801). Production lift
 * defaults `leadHours` to 12 (the spike's hard-coded value) and emits
 * the canonical slug suffix `-prog-12hr` so the recorded chart-spec mirror
 * at `data/charts/wx/wx-scenario-frontal-xc-march-prog-12hr/` remains the
 * regression baseline.
 */

import { advanceTruth } from '../truth/advance';
import type { TruthModel } from '../truth/types';
import type { ChartArtifact } from './types';

const DEFAULT_LEAD_HOURS = 12;

export function deriveProgChart(
	truth: TruthModel,
	scenarioId: string,
	leadHours: number = DEFAULT_LEAD_HOURS,
): ChartArtifact {
	const slug = `wx-scenario-${scenarioId}-prog-${leadHours}hr`;
	const cacheRelPath = `scenarios/${scenarioId}/prog-${leadHours}hr.json`;
	const projected = advanceTruth(truth, leadHours);

	const centers = projected.synoptic.pressureSystems.map((s) => ({
		kind: s.kind,
		lon: s.lon,
		lat: s.lat,
		pressureMb: s.centralPressureMb,
	}));
	const fronts = projected.synoptic.fronts.map((f) => ({
		kind: f.kind,
		points: f.points,
		pipSide: f.pipSide,
	}));

	const hazards = projected.hazardZones.map((hz) => {
		const ring = [...hz.polygon];
		const first = ring[0];
		const last = ring[ring.length - 1];
		if (first !== undefined && last !== undefined && (first[0] !== last[0] || first[1] !== last[1])) {
			ring.push(first);
		}
		const centroid = polygonCentroid(hz.polygon);
		const projectedKind: 'turbulence' | 'icing' | 'ifr' = hz.kind === 'mountain-obscuration' ? 'ifr' : hz.kind;
		return {
			id: `${hz.id}-${leadHours}h`,
			kind: projectedKind,
			label: `${projectedKind.toUpperCase()} forecast +${leadHours}h`,
			labelLonLat: centroid,
			rings: [ring],
		};
	});

	const sourceJson = {
		title: `${leadHours}hr prog VALID ${projected.validAt} -- truth-evolved from ${truth.validAt}`,
		validTimeIso: projected.validAt,
		forecastHours: leadHours,
		_source: 'Generated by wx-engine via truth-state advance.',
		centers,
		fronts,
		hazards,
	};

	const spec = {
		slug,
		type: 'prog-chart' as const,
		title: `${leadHours}hr Prog (truth-derived)`,
		subtitle: `Forecast valid ${projected.validAt} -- evolved from ${truth.validAt}`,
		projection: {
			kind: 'lambert' as const,
			parallels: [33, 45] as [number, number],
			rotate: [-96, -39] as [number, number],
		},
		extent: 'conus' as const,
		sources: {
			forecast: `cache://${cacheRelPath}`,
		},
		options: {
			isobar_interval_mb: 4,
			emphasize_every_mb: 8,
			show_h_l_markers: true,
			show_hazards: true,
			show_legend: true,
			source_attribution: 'wx-engine -- truth-derived synthetic forecast',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				path: cacheRelPath,
				bytes: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}

function polygonCentroid(poly: [number, number][]): [number, number] {
	let sx = 0;
	let sy = 0;
	for (const p of poly) {
		sx += p[0];
		sy += p[1];
	}
	const n = poly.length > 0 ? poly.length : 1;
	return [sx / n, sy / n];
}
