/**
 * Layer-3 surface-analysis chart spec derivation.
 *
 * Composes the wx-charts surface-analysis spec from
 *   - `truth.synoptic.pressureSystems` -> H/L centers
 *   - `truth.synoptic.fronts` -> front polylines + pip side
 *   - the derived METARs -> sparse station overlay with sky-cover / wind /
 *     pressure / temp / dewpoint per station
 *
 * The wx-charts library renders the spec via `renderSurfaceAnalysis`
 * (the schema is `surfaceAnalysisSpecSchema`). Source-byte shape matches
 * the renderer's source-data schema (`fronts: { centers, fronts, stations? }`).
 *
 * Lifted from the spike's pre-retirement
 * `spikes/wx-engine/src/charts/surface-analysis.ts` (PR #801 -- now
 * retired). The spike's spec validates against the wx-charts library
 * unchanged; the production lift replaces the spike's loose `{ cacheRelPath,
 * content }` source shape with the production `ChartArtifact.sources[].{path,bytes}`
 * shape that matches the bundle writer's expectations.
 */

import { wxScenarioChartSlug } from '@ab/constants';
import { CONUS_CENTRAL_MERIDIAN } from '@ab/wx-charts';
import type { DerivedMetar } from '../products/types';
import type { TruthModel } from '../truth/types';
import type { ChartArtifact } from './types';

type SkyCover = 'CLR' | 'FEW' | 'SCT' | 'BKN' | 'OVC';

export function deriveSurfaceAnalysisChart(
	truth: TruthModel,
	metars: DerivedMetar[],
	scenarioId: string,
): ChartArtifact {
	const slug = wxScenarioChartSlug(scenarioId, 'surface-analysis');
	const cacheRelPath = `scenarios/${scenarioId}/surface-analysis.json`;

	const centers = truth.synoptic.pressureSystems.map((s) => ({
		kind: s.kind,
		lon: s.lon,
		lat: s.lat,
		pressureMb: s.centralPressureMb,
	}));

	const fronts = truth.synoptic.fronts.map((f) => ({
		kind: f.kind,
		points: f.points,
		pipSide: f.pipSide,
	}));

	const stations = metars.map((m) => {
		const cToF = (c: number | null): number | undefined => (c === null ? undefined : Math.round((c * 9) / 5 + 32));
		const firstCloud = m.parsed.clouds[0];
		const rawSky = m.parsed.clouds.length === 0 ? 'CLR' : (firstCloud?.cover ?? 'CLR');
		const safeSky: SkyCover = isStationSkyCover(rawSky) ? rawSky : 'CLR';
		const wind = m.parsed.wind;
		return {
			id: m.parsed.station,
			lon: m.stationLon,
			lat: m.stationLat,
			tempF: cToF(m.parsed.tempC),
			dewF: cToF(m.parsed.dewpointC),
			pressureMb: m.parsed.altimeterInHg !== null ? Math.round(m.parsed.altimeterInHg * 33.8639) : undefined,
			windDir: wind?.directionDeg ?? null,
			windKt: wind?.speedKt ?? null,
			skyCover: safeSky,
		};
	});

	const sourceJson = {
		title: `Truth-derived surface analysis for ${scenarioId}`,
		validTimeIso: truth.validAt,
		_source: 'Generated by wx-engine from truth model.',
		_pattern_summary: truth.narrative,
		centers,
		fronts,
		stations,
	};

	const spec = {
		slug,
		type: 'surface-analysis' as const,
		title: 'Surface Analysis (truth-derived)',
		subtitle: `${truth.validAt} -- ${truth.narrative.slice(0, 80)}`,
		projection: {
			kind: 'lambert' as const,
			parallels: [33, 45] as [number, number],
			rotate: [CONUS_CENTRAL_MERIDIAN, 0] as [number, number],
		},
		extent: 'conus' as const,
		sources: {
			fronts: `cache://${cacheRelPath}`,
		},
		options: {
			station_density: 'hubs' as const,
			isobar_interval_mb: 4,
			emphasize_every_mb: 8,
			show_h_l_markers: true,
			source_attribution: 'wx-engine -- truth-derived synthetic',
		},
	};

	return {
		slug,
		spec,
		sources: [
			{
				path: cacheRelPath,
				bytes: JSON.stringify(sourceJson, null, 2),
			},
		],
	};
}

function isStationSkyCover(value: string): value is SkyCover {
	return value === 'CLR' || value === 'FEW' || value === 'SCT' || value === 'BKN' || value === 'OVC';
}
