/**
 * Phase D integration test -- spike-parity for the frontal-xc-march
 * commentary (WXENG-33).
 *
 * The recorded `data/wx-scenarios/frontal-xc-march/commentary.json` is the
 * regression baseline -- regenerated by `writeScenarioBundle` whenever
 * commentary code changes. This test pins the engine's runtime output to
 * the recorded file so a stray edit to the rule set surfaces as a test
 * failure rather than a silent drift in the bundle.
 *
 * Comparisons:
 *
 *   - `bundle.commentary.length` matches the recorded length.
 *   - Per-callout `id`, `target.kind`, `target.chartSlug`, `target.elementId`,
 *     `mode`, and `knowledgeNodeIds` match the recorded entries in order.
 *
 * Question / observation / reason text drifts under code change; the test
 * does not pin them line-for-line.
 */

import { describe, expect, it } from 'vitest';
import { generateScenario } from '../engine';

const REPO_ROOT = process.cwd();
const RECORDED_PATH = `${REPO_ROOT}/data/wx-scenarios/frontal-xc-march/commentary.json`;

interface RecordedCallout {
	id: string;
	target: { kind: string; chartSlug?: string; elementId?: string };
	mode: string;
	knowledgeNodeIds: string[];
}

function loadRecorded(): RecordedCallout[] {
	type GetBuiltinModule = (spec: string) => unknown;
	type NodeFs = { readFileSync: (p: string, enc: string) => string };
	const proc = process as NodeJS.Process & { getBuiltinModule?: GetBuiltinModule };
	const get = proc.getBuiltinModule;
	if (typeof get !== 'function') throw new Error('process.getBuiltinModule unavailable');
	const fs = get('node:fs') as NodeFs;
	const raw = fs.readFileSync(RECORDED_PATH, 'utf-8');
	return JSON.parse(raw) as RecordedCallout[];
}

describe('Phase D -- spike-parity (frontal-xc-march commentary)', () => {
	const bundle = generateScenario({ kind: 'frontal-xc-march' });
	const recorded = loadRecorded();

	it('length matches the recorded commentary.json (WXENG-33)', () => {
		expect(bundle.commentary.length).toBe(recorded.length);
	});

	it('per-callout id + target + mode + knowledgeNodeIds match the recorded entries', () => {
		expect(bundle.commentary.length).toBe(recorded.length);
		for (let i = 0; i < recorded.length; i += 1) {
			const got = bundle.commentary[i];
			const want = recorded[i];
			expect(got).toBeDefined();
			expect(want).toBeDefined();
			if (got === undefined || want === undefined) throw new Error(`missing entry at index ${i}`);
			expect(got.id).toBe(want.id);
			expect(got.target.kind).toBe(want.target.kind);
			expect(got.target.chartSlug).toBe(want.target.chartSlug);
			expect(got.target.elementId).toBe(want.target.elementId);
			expect(got.mode).toBe(want.mode);
			expect(got.knowledgeNodeIds).toEqual(want.knowledgeNodeIds);
		}
	});
});
