/**
 * Course BC -- instructor-authored courses, the peer primitive to syllabus.
 *
 * Read paths:
 *   - getCourseBySlug                 single-row by slug (returns null when missing)
 *   - getCourseStepsByCourse          every step in a course, ordered for tree walk
 *   - getCoursesByGoal                courses linked from a goal via goal_course
 *
 * Build/seed paths:
 *   - upsertCourse                    idempotent on slug (course-primitive seed)
 *   - upsertCourseStep                idempotent on (course_id, code)
 *
 * The session engine consumes courses indirectly through `getGoalNodeUnion`
 * in `./goals.ts`, which walks `goal_course -> course_step (level='step') ->
 * knowledge_node_id` and merges with goal_syllabus + goal_node into a single
 * deduped node set. Per-node weight is the max across reachable paths --
 * see the JSDoc on `getGoalNodeUnion` for the cross-source aggregation note.
 *
 * Course gap detection (`getCourseGaps`, this file) cross-references a course
 * against a cert syllabus and returns the cert leaves the course leaves
 * uncovered. The lens layer (`courseLens`, `courseWithCertOverlayLens` in
 * `./lenses-course.ts`) shares the same gap calculation: the overlay lens
 * delegates to `getCourseGaps` so both surfaces produce the same gap list.
 *
 * See `docs/work-packages/course-primitive/` and ADR 016 refinement
 * (2026-05-08) for the model rationale.
 */

import {
	type BloomLevel,
	COURSE_STATUSES,
	COURSE_STEP_LEVELS,
	type CourseKind,
	type CourseStatus,
	type CourseStepLevel,
	SYLLABUS_NODE_LEVELS,
} from '@ab/constants';
import { db as defaultDb } from '@ab/db/connection';
import { createId } from '@ab/utils';
import { and, asc, desc, eq, inArray, sql } from 'drizzle-orm';
import type { PgDatabase, PgQueryResultHKT } from 'drizzle-orm/pg-core';
import { UpsertReturnedNoRowError } from './errors';
import type { CertGap } from './lenses';
import {
	type CourseRow,
	type CourseStepRow,
	course,
	courseStep,
	type GoalCourseRow,
	type GoalRow,
	goalCourse,
	goalSyllabus,
	syllabusNode,
	syllabusNodeLink,
} from './schema';

type Db = PgDatabase<PgQueryResultHKT, Record<string, never>>;

// ---------------------------------------------------------------------------
// Read paths
// ---------------------------------------------------------------------------

/** Resolve a course by slug. Returns null when missing (callers usually want
 *  the lens-friendly "no row" path rather than a thrown error). */
export async function getCourseBySlug(slug: string, db: Db = defaultDb): Promise<CourseRow | null> {
	const rows = await db.select().from(course).where(eq(course.slug, slug)).limit(1);
	return rows[0] ?? null;
}

/**
 * Every step in a course, ordered so a tree walk produces sections before
 * their child steps and siblings come back in `ordinal` order.
 *
 * Sort key: `(parent_id NULLS FIRST, ordinal)` -- sections (parent_id NULL)
 * land before any step (parent_id non-null), then within each parent the
 * children come back in `ordinal` order. The two-level tree shape is
 * enforced at the schema layer (`course_step_consistency_check`), so a
 * caller can iterate the result list directly without re-checking levels.
 */
export async function getCourseStepsByCourse(courseId: string, db: Db = defaultDb): Promise<CourseStepRow[]> {
	// Postgres' default ASC order puts NULLs last; sections (parent_id NULL)
	// must come back before their child step rows so the caller can walk the
	// result as one pre-order tree. Explicit `NULLS FIRST` overrides the
	// default. Drizzle has no helper for nulls-ordering, so the sql template
	// stays small and direct.
	return db
		.select()
		.from(courseStep)
		.where(eq(courseStep.courseId, courseId))
		.orderBy(sql`${courseStep.parentId} ASC NULLS FIRST`, asc(courseStep.ordinal));
}

/**
 * Courses linked from a goal via `goal_course`. Returns the course rows
 * (not the link rows) ordered by course slug for stable read output.
 */
export async function getCoursesByGoal(goalId: string, db: Db = defaultDb): Promise<CourseRow[]> {
	const rows = await db
		.select({ course })
		.from(goalCourse)
		.innerJoin(course, eq(course.id, goalCourse.courseId))
		.where(eq(goalCourse.goalId, goalId))
		.orderBy(asc(course.slug));
	return rows.map((r) => r.course);
}

// ---------------------------------------------------------------------------
// Build / seed paths
// ---------------------------------------------------------------------------

/**
 * Input for {@link upsertCourse}. The course id is generated by the BC on
 * insert; idempotency is keyed on `slug` (UNIQUE in the schema). Re-running
 * with the same slug updates the existing row in place rather than failing
 * the unique constraint.
 */
export interface UpsertCourseInput {
	slug: string;
	kind: CourseKind;
	title: string;
	description?: string;
	status?: CourseStatus;
	seedOrigin?: string;
}

/**
 * Upsert a course by slug. Inserts a fresh `crs_` ULID id when the slug
 * is new; updates `kind / title / description / status / seedOrigin /
 * updatedAt` in place when the slug already exists. The returned row is
 * always the post-write state.
 */
export async function upsertCourse(input: UpsertCourseInput, db: Db = defaultDb): Promise<CourseRow> {
	const description = input.description ?? '';
	const status: CourseStatus = input.status ?? COURSE_STATUSES.ACTIVE;
	const seedOrigin = input.seedOrigin ?? null;
	const [row] = await db
		.insert(course)
		.values({
			id: createId('crs'),
			slug: input.slug,
			kind: input.kind,
			title: input.title,
			description,
			status,
			seedOrigin,
		})
		.onConflictDoUpdate({
			target: course.slug,
			set: {
				kind: input.kind,
				title: input.title,
				description,
				status,
				seedOrigin,
				updatedAt: new Date(),
			},
		})
		.returning();
	if (!row) throw new UpsertReturnedNoRowError('course', input.slug);
	return row;
}

/**
 * Input for {@link upsertCourseStep}. The step id is generated on insert;
 * idempotency is keyed on `(course_id, code)` (UNIQUE in the schema). The
 * BC sets `is_leaf` from `level` to keep the schema CHECK
 * (`course_step_consistency_check`) happy without trusting callers to
 * compute it correctly.
 */
export interface UpsertCourseStepInput {
	courseId: string;
	parentId: string | null;
	level: CourseStepLevel;
	ordinal: number;
	code: string;
	title: string;
	bodyMd: string;
	knowledgeNodeId: string | null;
	contentHash: string;
	seedOrigin?: string;
}

/**
 * Upsert a course step by `(course_id, code)`. The BC computes `is_leaf`
 * from `level` (`'step'` -> true, `'section'` -> false) so the schema CHECK
 * is always consistent regardless of caller input. Re-running with the same
 * `(course_id, code)` updates the row in place.
 *
 * The schema's `course_step_consistency_check` enforces the section vs step
 * shape (parent_id, knowledge_node_id, is_leaf). Callers that pass an
 * inconsistent shape (e.g. level='section' with a non-null knowledge_node_id)
 * surface the CHECK violation as a Postgres error -- the BC does not pre-
 * validate the shape because the seed pipeline has its own validator pass
 * upstream that catches the same thing with a friendlier message.
 */
export async function upsertCourseStep(input: UpsertCourseStepInput, db: Db = defaultDb): Promise<CourseStepRow> {
	const isLeaf = input.level === 'step';
	const seedOrigin = input.seedOrigin ?? null;
	const [row] = await db
		.insert(courseStep)
		.values({
			id: createId('cst'),
			courseId: input.courseId,
			parentId: input.parentId,
			level: input.level,
			ordinal: input.ordinal,
			code: input.code,
			title: input.title,
			bodyMd: input.bodyMd,
			knowledgeNodeId: input.knowledgeNodeId,
			isLeaf,
			contentHash: input.contentHash,
			seedOrigin,
		})
		.onConflictDoUpdate({
			target: [courseStep.courseId, courseStep.code],
			set: {
				parentId: input.parentId,
				level: input.level,
				ordinal: input.ordinal,
				title: input.title,
				bodyMd: input.bodyMd,
				knowledgeNodeId: input.knowledgeNodeId,
				isLeaf,
				contentHash: input.contentHash,
				seedOrigin,
				updatedAt: new Date(),
			},
		})
		.returning();
	if (!row) throw new UpsertReturnedNoRowError('course_step', `${input.courseId}:${input.code}`);
	return row;
}

// ---------------------------------------------------------------------------
// Cert overlay -- gap detection
// ---------------------------------------------------------------------------

/**
 * Cert leaves required by a syllabus that no step in the course covers.
 *
 * Algorithm:
 *
 *   1. Collect every leaf `syllabus_node` rooted under `syllabusId` (level
 *      `'element'` AND `is_leaf = true` -- the ACS / PTS leaf shape).
 *   2. For every leaf, collect its linked `knowledge_node_id` set via
 *      `syllabus_node_link`. Multi-link leaves carry every linked node.
 *   3. Collect the set of `knowledge_node_id` reached by the course (every
 *      `course_step` row at `level='step'` under `courseId`).
 *   4. Emit a {@link CertGap} for every cert leaf where NONE of its linked
 *      knowledge nodes appear in the course's covered set. Leaves with zero
 *      authored links count as gaps too -- the course can't possibly cover
 *      a leaf that lists no knowledge nodes.
 *
 * The `goalId` parameter is reserved for future per-goal weighting; the
 * current calculation is goal-agnostic (a gap is a gap regardless of which
 * goal the learner holds, and the overlay lens accepts a syllabus id that the
 * goal does not reference). Kept on the signature so the lens / non-tree
 * consumers that call `getCourseGaps` stay shape-stable when goal-aware
 * weighting lands.
 *
 * Output is stable-sorted by syllabus_node `(level, ordinal, code)` so the
 * UI renders gaps in cert-traversal order regardless of insert order. When
 * the syllabus does not exist or has no leaves, returns `[]`.
 *
 * Pure read; no writes. Safe to call from a route loader on every render.
 */
export async function getCourseGaps(
	_goalId: string,
	courseId: string,
	syllabusId: string,
	db: Db = defaultDb,
): Promise<CertGap[]> {
	// Step 1: every cert leaf rooted under the syllabus.
	const leafRows = await db
		.select({
			id: syllabusNode.id,
			code: syllabusNode.code,
			title: syllabusNode.title,
			ordinal: syllabusNode.ordinal,
			requiredBloom: syllabusNode.requiredBloom,
		})
		.from(syllabusNode)
		.where(
			and(
				eq(syllabusNode.syllabusId, syllabusId),
				eq(syllabusNode.level, SYLLABUS_NODE_LEVELS.ELEMENT),
				eq(syllabusNode.isLeaf, true),
			),
		);
	if (leafRows.length === 0) return [];

	// Step 2: every leaf -> knowledge_node link in one round trip.
	const leafIds = leafRows.map((l) => l.id);
	const linkRows =
		leafIds.length === 0
			? []
			: await db
					.select({
						leafId: syllabusNodeLink.syllabusNodeId,
						knowledgeNodeId: syllabusNodeLink.knowledgeNodeId,
					})
					.from(syllabusNodeLink)
					.where(inArray(syllabusNodeLink.syllabusNodeId, leafIds));
	const knowledgeIdsByLeaf = new Map<string, string[]>();
	for (const id of leafIds) knowledgeIdsByLeaf.set(id, []);
	for (const r of linkRows) {
		const list = knowledgeIdsByLeaf.get(r.leafId);
		if (list === undefined) continue;
		list.push(r.knowledgeNodeId);
	}

	// Step 3: every knowledge_node covered by the course (level='step').
	// Pulls only `knowledge_node_id` because we only need the set, not the
	// row shape.
	const stepRows = await db
		.select({ knowledgeNodeId: courseStep.knowledgeNodeId })
		.from(courseStep)
		.where(and(eq(courseStep.courseId, courseId), eq(courseStep.level, COURSE_STEP_LEVELS.STEP)));
	const coveredNodes = new Set<string>();
	for (const r of stepRows) {
		if (r.knowledgeNodeId !== null) coveredNodes.add(r.knowledgeNodeId);
	}

	// Step 4: emit a gap for every leaf where NO linked knowledge node is
	// covered. Stable sort by (ordinal, code) so the output reads like a
	// cert traversal even when the lower-level scan returned rows in a
	// different order. The pre-sort ordinal lookup uses the source rows so
	// the `requiredBloom` cast and the sort compare share the same row
	// without an O(n) scan per compare.
	const ordinalByLeaf = new Map<string, number>();
	for (const leaf of leafRows) ordinalByLeaf.set(leaf.id, leaf.ordinal);

	const gaps: CertGap[] = [];
	for (const leaf of leafRows) {
		const linked = knowledgeIdsByLeaf.get(leaf.id) ?? [];
		const isCovered = linked.some((nodeId) => coveredNodes.has(nodeId));
		if (isCovered) continue;
		gaps.push({
			syllabusNodeId: leaf.id,
			code: leaf.code,
			title: leaf.title,
			requiredBloom: (leaf.requiredBloom as BloomLevel | null) ?? null,
			knowledgeNodeIds: linked,
		});
	}
	gaps.sort((a, b) => {
		const ordinalA = ordinalByLeaf.get(a.syllabusNodeId) ?? 0;
		const ordinalB = ordinalByLeaf.get(b.syllabusNodeId) ?? 0;
		if (ordinalA !== ordinalB) return ordinalA - ordinalB;
		// Two leaves with identical ordinals but distinct codes fall through
		// to the lexical code compare so the output stays deterministic
		// across re-runs.
		return a.code.localeCompare(b.code);
	});
	return gaps;
}

// ---------------------------------------------------------------------------
// Reader / editor read-helpers (course-reader-and-editor WP)
// ---------------------------------------------------------------------------

/** Filter options for {@link listCoursesForReader}. */
export interface ListCoursesForReaderOpts {
	/**
	 * When set, restrict the result to courses whose `status` is in this list.
	 * Defaults to `['active', 'archived']` -- drafts are hidden from the
	 * study reader by default. Pass `[...COURSE_STATUS_VALUES]` to include
	 * drafts (the hangar editor uses {@link listAllCourses} instead).
	 */
	statusIn?: readonly CourseStatus[];
}

/**
 * List courses for the study reader. Filters by status (drafts excluded by
 * default). Sorted by title ascending so the index page renders deterministically.
 *
 * Pure read; safe to call from a route loader on every render. Used by the
 * `/courses` index page (`apps/study/src/routes/(app)/courses/+page.server.ts`).
 */
export async function listCoursesForReader(
	db: Db = defaultDb,
	opts: ListCoursesForReaderOpts = {},
): Promise<CourseRow[]> {
	const statusIn = opts.statusIn ?? [COURSE_STATUSES.ACTIVE, COURSE_STATUSES.ARCHIVED];
	if (statusIn.length === 0) return [];
	return db
		.select()
		.from(course)
		.where(inArray(course.status, statusIn as CourseStatus[]))
		.orderBy(asc(course.title));
}

/**
 * List every course in the system regardless of status. Used by the hangar
 * editor's `/courses` index page; the editor surfaces all statuses (draft +
 * active + archived) so authors can iterate on draft work.
 *
 * Sorted by `updatedAt` descending so the most-recently-edited course is
 * surfaced first -- matches the hangar /glossary pattern.
 */
export async function listAllCourses(db: Db = defaultDb): Promise<CourseRow[]> {
	return db.select().from(course).orderBy(desc(course.updatedAt));
}

/**
 * Resolve a course by its primary id. Returns null when missing -- callers
 * (the hangar manifest editor's loader, the orphan-cleanup action) handle
 * the missing-row case explicitly.
 */
export async function getCourseById(id: string, db: Db = defaultDb): Promise<CourseRow | null> {
	const rows = await db.select().from(course).where(eq(course.id, id)).limit(1);
	return rows[0] ?? null;
}

/**
 * Resolve a single course step by `(course_id, code)`. Returns null when
 * missing. Used by the step-reader page's loader to resolve a `:slug/:stepCode`
 * URL pair without scanning the entire course tree.
 */
export async function getCourseStepByCode(
	courseId: string,
	code: string,
	db: Db = defaultDb,
): Promise<CourseStepRow | null> {
	const rows = await db
		.select()
		.from(courseStep)
		.where(and(eq(courseStep.courseId, courseId), eq(courseStep.code, code)))
		.limit(1);
	return rows[0] ?? null;
}

/**
 * Delete a single course_step row by id. Used by the hangar orphan-cleanup
 * action; the FK to `knowledge_node` is RESTRICT but the row itself can be
 * deleted any time -- the cascade on `course.id` handles the parent-side.
 */
export async function deleteCourseStep(id: string, db: Db = defaultDb): Promise<void> {
	await db.delete(courseStep).where(eq(courseStep.id, id));
}

/**
 * Delete a course row by id. Cascades to every `course_step` row under the
 * course (`onDelete: 'cascade'` on `course_step.course_id`) AND to every
 * `goal_course` row that linked to the course (`onDelete: 'cascade'` on
 * `goal_course.goal_id` would not fire here -- the FK on
 * `goal_course.course_id` is `onDelete: 'restrict'`, so a course that is
 * still in any goal will reject this delete with a Postgres FK error). The
 * hangar editor's delete-course flow checks `goal_course` before invoking
 * this helper and surfaces the FK rejection as a form error if it slips
 * through.
 */
export async function deleteCourseRow(id: string, db: Db = defaultDb): Promise<void> {
	await db.delete(course).where(eq(course.id, id));
}

/**
 * Pick the syllabus the cert-overlay should run against, given a learner's
 * goal. The selection rule (deterministic so the overlay is stable across
 * refreshes):
 *
 *   1. Highest-weight `goal_syllabus.weight` row.
 *   2. Tie-break by `syllabus_id` ascending (lexicographic).
 *
 * Returns null when the goal is null OR has no `goal_syllabus` rows. The
 * detail-page loader uses this to choose between `courseLens` (no overlay)
 * and `courseWithCertOverlayLens` (overlay against the picked syllabus).
 *
 * A user-facing syllabus picker is deferred (see
 * `docs/work-packages/course-reader-and-editor/OUT-OF-SCOPE.md` -- "Multi-
 * syllabus overlay picker"). When that lands the picker overrides this
 * auto-pick via a `?cert=<id>` query param.
 */
export async function pickOverlaySyllabus(goal: GoalRow | null, db: Db = defaultDb): Promise<string | null> {
	if (goal === null) return null;
	const rows = await db
		.select({ syllabusId: goalSyllabus.syllabusId, weight: goalSyllabus.weight })
		.from(goalSyllabus)
		.where(eq(goalSyllabus.goalId, goal.id))
		.orderBy(desc(goalSyllabus.weight), asc(goalSyllabus.syllabusId))
		.limit(1);
	return rows[0]?.syllabusId ?? null;
}

// ---------------------------------------------------------------------------
// Goal-course composition (course-reader-and-editor WP -- mirrors the
// goal_syllabus helpers in `./goals.ts`)
// ---------------------------------------------------------------------------

/**
 * Add a course to a goal. Idempotent on the `(goal_id, course_id)` composite
 * PK -- re-running with a different weight updates the weight in place.
 *
 * Validation lives at the route layer (the form action checks course
 * existence + status='active' + already-in-goal explicitly). This helper is
 * the thin write path; it does not parse a Zod schema because callers
 * already did the per-action validation upstream and the column-level CHECK
 * (`goal_course_weight_check`) backs up the weight bound at the DB layer.
 */
export async function addGoalCourse(
	goalId: string,
	courseId: string,
	weight: number,
	db: Db = defaultDb,
): Promise<void> {
	await db
		.insert(goalCourse)
		.values({ goalId, courseId, weight, seedOrigin: null, createdAt: new Date() })
		.onConflictDoUpdate({
			target: [goalCourse.goalId, goalCourse.courseId],
			set: { weight },
		});
}

/** Remove a course from a goal. No-op when not linked. */
export async function removeGoalCourse(goalId: string, courseId: string, db: Db = defaultDb): Promise<void> {
	await db.delete(goalCourse).where(and(eq(goalCourse.goalId, goalId), eq(goalCourse.courseId, courseId)));
}

/**
 * Update the weight on an existing `goal_course` row. Silent no-op when the
 * `(goalId, courseId)` pair has no row (the form action checks existence
 * first; this matches the `setGoalSyllabusWeight` shape).
 */
export async function setGoalCourseWeight(
	goalId: string,
	courseId: string,
	weight: number,
	db: Db = defaultDb,
): Promise<void> {
	await db
		.update(goalCourse)
		.set({ weight })
		.where(and(eq(goalCourse.goalId, goalId), eq(goalCourse.courseId, courseId)));
}

/**
 * Check whether a goal already has a row for a given course. Used by the
 * `addCourse` form action to surface "Course already in goal" before
 * attempting the upsert (the upsert would silently update weight, which
 * is the wrong UX for a duplicate add).
 */
export async function goalHasCourse(goalId: string, courseId: string, db: Db = defaultDb): Promise<boolean> {
	const rows = await db
		.select({ goalId: goalCourse.goalId })
		.from(goalCourse)
		.where(and(eq(goalCourse.goalId, goalId), eq(goalCourse.courseId, courseId)))
		.limit(1);
	return rows.length > 0;
}

/**
 * Goal-course link rows for a goal, ordered by `course_id` ASC for stable
 * read output. Mirrors {@link getGoalSyllabi} -- returns the link rows
 * (with `weight`), not the joined course rows. Loaders that need both
 * the link weights and the course metadata pair this with
 * {@link getCoursesByGoal} (which returns the joined course rows alone).
 */
export async function getGoalCourses(goalId: string, db: Db = defaultDb): Promise<GoalCourseRow[]> {
	return db.select().from(goalCourse).where(eq(goalCourse.goalId, goalId)).orderBy(asc(goalCourse.courseId));
}

/**
 * Section counts for a list of courses, returned as `{ courseId -> count }`.
 * The hangar courses index uses this to render `section_count` per row
 * without N round-trips. Sections are `course_step` rows with
 * `level='section'`; steps are excluded.
 */
export async function getSectionCountsByCourseIds(
	courseIds: readonly string[],
	db: Db = defaultDb,
): Promise<Record<string, number>> {
	if (courseIds.length === 0) return {};
	const rows = await db
		.select({ courseId: courseStep.courseId, count: sql<number>`COUNT(*)::int` })
		.from(courseStep)
		.where(and(inArray(courseStep.courseId, courseIds), eq(courseStep.level, COURSE_STEP_LEVELS.SECTION)))
		.groupBy(courseStep.courseId);
	const out: Record<string, number> = {};
	for (const id of courseIds) out[id] = 0;
	for (const r of rows) out[r.courseId] = r.count;
	return out;
}
