// Study BC -- spaced repetition, cards, reviews, scenarios, calibration,
// and the polymorphic content-citation surface (folded in from the former
// citations package; see docs/work-packages/bc-citations-coupling/).

export type {
	CalibrationBucket,
	CalibrationPageData,
	CalibrationResult,
	CalibrationTrendPoint,
	DomainCalibration,
} from './calibration';
export {
	getCalibration,
	getCalibrationPageData,
	getCalibrationPointCount,
	getCalibrationTrend,
} from './calibration';
export type {
	CardCrossReferences,
	CardCrossRefsPlans,
	CardCrossRefsReps,
	CardCrossRefsScenarios,
} from './card-cross-references';
export { CROSS_REF_SESSION_LIMIT, getCardCrossReferences } from './card-cross-references';
export type {
	CardFilters,
	CardsFacetCounts,
	CardWithState,
	CreateCardInput,
	RemovedCardRow,
	RemovedCardsFilters,
	UpdateCardInput,
} from './cards';
export {
	CardNotEditableError,
	CardNotFoundError,
	createCard,
	getCard,
	getCards,
	getCardsCount,
	getCardsFacetCounts,
	getDueCards,
	getRemovedCards,
	getRemovedCardsCount,
	SourceRefRequiredError,
	setCardStatus,
	updateCard,
} from './cards';
export type { PublicCard, PublicCardCitation } from './cards-public';
export { composePublicCardCitations, getPublicCard } from './cards-public';
export {
	CitationNotFoundError,
	CitationSourceNotFoundError,
	CitationTargetNotFoundError,
	CitationValidationError,
	type CitationWithSource,
	type CitationWithTarget,
	type ContentCitationRow,
	type CreateCitationInput,
	contentCitation,
	createCitation,
	DuplicateCitationError,
	deleteCitation,
	getCitationsOf,
	getCitedBy,
	type NewContentCitationRow,
	type RegulationSearchResult,
	resolveCitationSources,
	resolveCitationTargets,
	searchAcReferences,
	searchKnowledgeNodes,
	searchRegulationNodes,
} from './citations';
export type {
	AreaMasteryRollup,
	CredentialDagSnapshot,
	CredentialMasteryRollup,
	ListCredentialsOptions,
} from './credentials';
export {
	CredentialNotFoundError,
	CredentialPrereqCycleError,
	getCertsCoveredBy,
	getCredentialById,
	getCredentialBySlug,
	getCredentialIdsCoveredBy,
	getCredentialMastery,
	getCredentialPrereqDag,
	getCredentialPrereqs,
	getCredentialPrimarySyllabus,
	getCredentialSyllabi,
	listCredentials,
	upsertCredential,
	upsertCredentialPrereq,
	upsertCredentialSyllabus,
	validateCredentialDag,
} from './credentials';
export type {
	ActivityDay,
	DashboardFetchers,
	DashboardPayload,
	PanelResult,
	RecentActivity,
	RepBacklog,
	RepBacklogDomain,
	WeakArea,
	WeakAreaReason,
} from './dashboard';
export {
	getDashboardPayload,
	getRecentActivity,
	getRepBacklog,
	getWeakAreas,
	overdueCutoff,
} from './dashboard';
export {
	canonicalDeckSpecJson,
	computeDeckHash,
	DeckSpecDecodeError,
	decodeDeckSpec,
	encodeDeckSpec,
	normalizeDeckSpec,
	summarizeDeckSpec,
} from './deck-spec';
export { runEngine } from './engine';
export type { SubmitFeedbackInput } from './feedback';
export { FeedbackCommentRequiredError, getLatestFeedback, submitFeedback } from './feedback';
export { formatNextInterval, formatNextIntervalAbsolute } from './formatters';
export type { CreateGoalParams, ListGoalsOptions as ListGoalsOpts } from './goals';
export {
	addGoalNode,
	addGoalSyllabus,
	archiveGoal,
	createGoal,
	GoalAlreadyPrimaryError,
	GoalNotFoundError,
	GoalNotOwnedError,
	getActiveGoals,
	getDerivedCertGoals,
	getGoalById,
	getGoalNodes,
	getGoalNodeUnion,
	getGoalSyllabi,
	getOwnedGoal,
	getPrimaryGoal,
	listGoals,
	removeGoalNode,
	removeGoalSyllabus,
	setGoalNodeWeight,
	setGoalSyllabusWeight,
	setPrimaryGoal,
	updateGoal,
} from './goals';
export {
	citationSchema,
	type HandbookManifest,
	type HandbookManifestFigure,
	type HandbookManifestSection,
	type HandbookManifestWarning,
	type HandbookSectionFrontmatter,
	handbookHeartbeatInputSchema,
	handbookManifestFigureSchema,
	handbookManifestSchema,
	handbookManifestSectionSchema,
	handbookManifestWarningSchema,
	handbookNotesInputSchema,
	handbookReadStatusSchema,
	handbookSectionFrontmatterSchema,
	legacyCitationSchema,
	structuredCitationSchema,
} from './handbook-validation';
// Handbook ingestion + reader (ADR 016 phase 0).
export type {
	CitingNodesQuery,
	GetReferenceOptions,
	HandbookProgressSummary,
	HandbookSectionView,
	ListReferencesOptions,
} from './handbooks';
export {
	getHandbookChapter,
	getHandbookProgress,
	getHandbookSection,
	getNodesCitingSection,
	getReadState,
	getReferenceByDocument,
	getReferenceById,
	HandbookSectionNotFoundError,
	HandbookValidationError,
	listAllSectionsForReference,
	listChapterSections,
	listFiguresForSection,
	listHandbookChapters,
	listReferences,
	markAsReread,
	ReferenceNotFoundError,
	recordHeartbeat,
	resolveCitationUrl,
	setComprehended,
	setNotes,
	setReadStatus,
} from './handbooks';
export type {
	CertAndDomainMatrix,
	CertProgress,
	DomainCertCell,
	DomainCertRow,
	KnowledgeFacetCounts,
	KnowledgeNodeListRow,
	ListNodesFilters,
	NodeMasteryGate,
	NodeMasterySnapshot,
	NodeMasteryStats,
	NodePhaseProgress,
	NodeSummary,
	NodeView,
} from './knowledge';
export {
	computeCardGate,
	computeDisplayScore,
	computeRepGate,
	findRequiresCycle,
	getCardsForNode,
	getCertAndDomainMatrix,
	getCertProgress,
	getDomainCertMatrix,
	getNodeMastery,
	getNodeMasteryMap,
	getNodeProgress,
	getNodesByIds,
	getNodeView,
	isMastered,
	isNodeMastered,
	KnowledgeGraphCycleError,
	KnowledgeNodeNotFoundError,
	lifecycleFromContent,
	listNodeIds,
	listNodeSummaries,
	listNodesForBrowse,
	listNodesWithFacets,
	recordPhaseCompleted,
	recordPhaseVisited,
	refreshEdgeTargetExists,
	replaceNodeEdges,
	splitContentPhases,
	upsertKnowledgeNode,
} from './knowledge';
export type {
	AcsLensFilters,
	DomainLensFilters,
	Lens,
	LensInput,
	LensLeaf,
	LensResult,
	LensTreeNode,
	MasteryRollup,
} from './lenses';
export { acsLens, computeMasteryRollup, domainLens, LensError } from './lenses';
export type { CreatePlanInput, UpdatePlanInput } from './plans';
export {
	activatePlan,
	addSkipDomain,
	addSkipNode,
	archivePlan,
	createPlan,
	DomainOverlapError,
	DuplicateActivePlanError,
	getActivePlan,
	getPlan,
	getPlans,
	NoActivePlanError,
	PlanNotFoundError,
	removeSkipDomain,
	removeSkipNode,
	updatePlan,
} from './plans';
export type {
	CardSessionRef,
	ReviewSessionCard,
	ReviewSessionState,
	SavedDeckSummary,
	StartReviewSessionInput,
} from './review-sessions';
export {
	abandonStaleSessions,
	advanceReviewSession,
	findResumableSessionByDeckHash,
	getLatestResumableSession,
	getReviewedCardIdsInSession,
	getSessionsForCard,
	jumpToIndex,
	listSavedDecks,
	ReviewSessionJumpOutOfRangeError,
	ReviewSessionNotActiveError,
	ReviewSessionNotFoundError,
	replaceSessionAtIndex,
	resumeReviewSession,
	shrinkSessionAtIndex,
	startReviewSession,
} from './review-sessions';
export type { SubmitReviewInput } from './reviews';
export { CardNotReviewableError, NoReviewToUndoError, submitReview, undoReview } from './reviews';
export {
	deleteSavedDeck,
	getSavedDeckOverlays,
	normalizeSavedDeckLabel,
	renameSavedDeck,
	SavedDeckLabelTooLongError,
} from './saved-decks';
export type {
	CreateScenarioInput,
	DomainAccuracyStats,
	RepAccuracyStats,
	RepAttemptOutcome,
	RepDashboardStats,
	RepStats,
	ScenarioFilters,
	ScenariosFacetCounts,
	SubmitAttemptInput,
} from './scenarios';
export {
	createScenario,
	getDomainAccuracy,
	getNextScenarios,
	getRepAccuracy,
	getRepDashboard,
	getRepStats,
	getScenario,
	getScenarios,
	getScenariosCount,
	getScenariosFacetCounts,
	InvalidOptionError,
	ScenarioNotAttemptableError,
	ScenarioNotFoundError,
	setScenarioStatus,
	submitAttempt,
} from './scenarios';
// Drizzle table objects + row types. Table objects are exported for scripts
// and seed code; route handlers should prefer BC functions and never issue
// raw db.insert/select on these tables.
export type {
	CardFeedbackRow,
	CardRow,
	CardSnoozeRow,
	CardStateRow,
	CredentialPrereqRow,
	CredentialRow,
	CredentialSyllabusRow,
	GoalNodeRow,
	GoalRow,
	GoalSyllabusRow,
	HandbookFigureRow,
	HandbookReadStateRow,
	HandbookSectionRow,
	KnowledgeEdgeRow,
	KnowledgeNodeProgressRow,
	KnowledgeNodeRow,
	MemoryReviewSessionRow,
	NewCardFeedbackRow,
	NewCardRow,
	NewCardSnoozeRow,
	NewCardStateRow,
	NewCredentialPrereqRow,
	NewCredentialRow,
	NewCredentialSyllabusRow,
	NewGoalNodeRow,
	NewGoalRow,
	NewGoalSyllabusRow,
	NewHandbookFigureRow,
	NewHandbookReadStateRow,
	NewHandbookSectionRow,
	NewKnowledgeEdgeRow,
	NewKnowledgeNodeProgressRow,
	NewKnowledgeNodeRow,
	NewMemoryReviewSessionRow,
	NewReferenceRow,
	NewReviewRow,
	NewSavedDeckRow,
	NewScenarioRow,
	NewSessionItemResultRow,
	NewSessionRow,
	NewStudyPlanRow,
	NewSyllabusNodeLinkRow,
	NewSyllabusNodeRow,
	NewSyllabusRow,
	ReferenceRow,
	ReviewRow,
	ReviewSessionDeckSpec,
	SavedDeckRow,
	ScenarioOption,
	ScenarioRow,
	SessionItem,
	SessionItemResultRow,
	SessionRow,
	StudyPlanRow,
	SyllabusNodeLinkRow,
	SyllabusNodeRow,
	SyllabusRow,
} from './schema';
export {
	card,
	cardFeedback,
	cardSnooze,
	cardState,
	credential,
	credentialPrereq,
	credentialSyllabus,
	goal,
	goalNode,
	goalSyllabus,
	knowledgeEdge,
	knowledgeNode,
	knowledgeNodeProgress,
	memoryReviewSession,
	review,
	savedDeck,
	scenario,
	session,
	sessionItemResult,
	studyPlan,
	studySchema,
	syllabus,
	syllabusNode,
	syllabusNodeLink,
} from './schema';
export type {
	ItemResultInput,
	PreviewOptions,
	SessionPreview,
	SessionSuggestedAction,
	SessionSummary,
	SessionSummarySliceRow,
	SkipSessionSlotInput,
} from './sessions';
export {
	buildEnginePools,
	commitSession,
	completeSession,
	getResumableSession,
	getSession,
	getSessionItemResult,
	getSessionItemResults,
	getSessionSummary,
	getSessions,
	getStreakDays,
	previewSession,
	recordItemResult,
	SessionNotFoundError,
	SessionSlotNotFoundError,
	skipSessionSlot,
	startSession,
} from './sessions';
export type { SimScenarioNodeMappings } from './sim-bias';
export { aggregateSimNodePressure, simWeaknessByNode } from './sim-bias';
export type { RemoveCardInput, ReplacementCardResult, RestoreCardInput, SnoozeCardInput } from './snooze';
export {
	CardAlreadyRemovedError,
	getActiveSnoozes,
	getReplacementCard,
	getUnresolvedReEntrySnooze,
	markCardEditedForActiveBadQuestionSnoozes,
	removeCard,
	resolveBadQuestionSnooze,
	restoreCard,
	restoreCardByCard,
	SnoozeCommentRequiredError,
	SnoozeNotFoundError,
	snoozeCard,
} from './snooze';
export type { CardSchedulerState, ScheduleResult } from './srs';
export { fsrsDefaultParams, fsrsInitialState, fsrsPreviewAll, fsrsSchedule } from './srs';
export type {
	DashboardStats,
	DomainStats,
	MasteryStats,
	RecentAttemptRow,
	RecentReviewRow,
	ReviewStats,
} from './stats';
export {
	getCardMastery,
	getDashboardStats,
	getDomainBreakdown,
	getDueCardCount,
	getMasteredCount,
	getRecentAttemptsForScenario,
	getRecentReviewsForCard,
	getReviewStats,
} from './stats';
export type {
	ListSyllabiOptions,
	SyllabusAreaView,
	SyllabusLeafWithSyllabus,
	SyllabusTreeNode,
	SyllabusTreeValidationInput,
} from './syllabi';
export {
	AirbossRefValidationError,
	buildSyllabusTreeFromRows,
	getCitationsForSyllabusNode,
	getKnowledgeNodesForSyllabusLeaf,
	getSyllabusArea,
	getSyllabusById,
	getSyllabusBySlug,
	getSyllabusLeaves,
	getSyllabusLeavesForKnowledgeNode,
	getSyllabusTree,
	levelIsLeafEligible,
	listSyllabi,
	replaceSyllabusNodeLinks,
	SyllabusNotFoundError,
	SyllabusValidationError,
	upsertSyllabus,
	upsertSyllabusNode,
	validateAirbossRefForLeaf,
	validateSyllabusTree,
} from './syllabi';
export {
	cardTagsSchema,
	cardTextSchema,
	confidenceSchema,
	type NewCardInput,
	type NewScenarioInput,
	newCardSchema,
	newScenarioSchema,
	regReferencesSchema,
	reviewRatingSchema,
	scenarioOptionSchema,
	scenarioOptionsSchema,
	submitAttemptSchema,
	submitReviewSchema,
	updateCardSchema,
} from './validation';
