// @browser-globals: server-only -- never imported by client .svelte
/**
 * Encoded-text catalog loader for the wx products examples page.
 *
 * Reads `course/knowledge/weather/encoded-text-catalog/catalog.json` once
 * per server process and exposes typed per-product projections. The JSON
 * file is generated by `bun tools/catalog-build/bin.ts` from the
 * `course/knowledge/weather/encoded-text-catalog/<product>.md` source
 * files; `bun run check` rejects a stale catalog so what's on disk is
 * always the source of truth for the examples page.
 *
 * Server-only -- uses `node:fs` and `node:path` directly. Safe inside
 * `+page.server.ts` because the SvelteKit bundler never ships server
 * modules to the client. The `@browser-globals: server-only` tag at the
 * top documents that intent for the lint walker.
 */

import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

/** Slug used in the URL for each product page. */
export const WX_CATALOG_PRODUCT_SLUGS = ['metar', 'taf', 'pirep', 'fb', 'airmet-sigmet'] as const;
export type WxCatalogProductSlug = (typeof WX_CATALOG_PRODUCT_SLUGS)[number];

/** Key inside `catalog.json` `products: {...}` for each product slug. */
const PRODUCT_KEY_BY_SLUG: Record<WxCatalogProductSlug, keyof CatalogProductsRaw> = {
	metar: 'metar',
	taf: 'taf',
	pirep: 'pirep',
	fb: 'fb',
	'airmet-sigmet': 'airmetSigmet',
};

/** Display label per product slug (used in breadcrumbs and headers). */
export const WX_CATALOG_PRODUCT_LABELS: Record<WxCatalogProductSlug, string> = {
	metar: 'METAR',
	taf: 'TAF',
	pirep: 'PIREP',
	fb: 'FB (Winds and Temperatures Aloft)',
	'airmet-sigmet': 'AIRMET / SIGMET',
};

const REPO_ROOT = resolve(import.meta.dirname, '..', '..', '..', '..', '..', '..', '..', '..');
const CATALOG_PATH = resolve(REPO_ROOT, 'course/knowledge/weather/encoded-text-catalog/catalog.json');

interface CatalogReferenceRaw {
	source: string;
	detail: string;
}

interface CatalogTokenFamilyRaw {
	slug: string;
	label: string;
	decode: string;
	references: CatalogReferenceRaw[];
	examples: string[];
}

interface CatalogExampleRaw {
	slug: string;
	product: string;
	raw: string;
	tokenFamilies: string[];
	synoptic: string;
	triageDrivers: string[];
	references: CatalogReferenceRaw[];
}

interface CatalogProductRaw {
	product: string;
	tokenFamilies: CatalogTokenFamilyRaw[];
	examples: CatalogExampleRaw[];
}

interface CatalogProductsRaw {
	metar: CatalogProductRaw;
	taf: CatalogProductRaw;
	pirep: CatalogProductRaw;
	fb: CatalogProductRaw;
	airmetSigmet: CatalogProductRaw;
}

interface CatalogRaw {
	generatedAt: string;
	products: CatalogProductsRaw;
}

/** One reference (source + section) attached to a family or example. */
export interface WxCatalogReference {
	readonly source: string;
	readonly detail: string;
}

/** One token-family chip definition for the filter row. */
export interface WxCatalogTokenFamily {
	readonly slug: string;
	readonly label: string;
	readonly decode: string;
	readonly references: ReadonlyArray<WxCatalogReference>;
	/** Number of examples in this product that exercise the family. */
	readonly exampleCount: number;
}

/** One example card. */
export interface WxCatalogExample {
	readonly slug: string;
	readonly raw: string;
	readonly tokenFamilies: ReadonlyArray<string>;
	readonly synoptic: string;
	readonly triageDrivers: ReadonlyArray<string>;
	readonly references: ReadonlyArray<WxCatalogReference>;
}

/** Full per-product projection used by the examples page loader. */
export interface WxCatalogProduct {
	readonly slug: WxCatalogProductSlug;
	readonly label: string;
	readonly tokenFamilies: ReadonlyArray<WxCatalogTokenFamily>;
	readonly examples: ReadonlyArray<WxCatalogExample>;
}

let cache: CatalogRaw | null = null;
let cachePromise: Promise<CatalogRaw> | null = null;

async function loadCatalogRaw(): Promise<CatalogRaw> {
	if (cache !== null) return cache;
	if (cachePromise !== null) return cachePromise;
	cachePromise = (async () => {
		const text = await readFile(CATALOG_PATH, 'utf8');
		const parsed = JSON.parse(text) as CatalogRaw;
		cache = parsed;
		cachePromise = null;
		return parsed;
	})();
	return cachePromise;
}

/** True when `slug` is one of the supported product slugs. */
export function isWxCatalogProductSlug(slug: string): slug is WxCatalogProductSlug {
	return (WX_CATALOG_PRODUCT_SLUGS as ReadonlyArray<string>).includes(slug);
}

/**
 * Load one product's catalog projection. Returns `null` if the slug is
 * recognized but the product has zero authored families (which would
 * indicate a build problem -- the caller renders a 404 in that case).
 */
export async function loadWxCatalogProduct(slug: WxCatalogProductSlug): Promise<WxCatalogProduct | null> {
	const raw = await loadCatalogRaw();
	const productRaw = raw.products[PRODUCT_KEY_BY_SLUG[slug]];
	if (!productRaw) return null;
	if (productRaw.tokenFamilies.length === 0 && productRaw.examples.length === 0) return null;

	// Count examples per family for chip counts.
	const counts = new Map<string, number>();
	for (const ex of productRaw.examples) {
		for (const fam of ex.tokenFamilies) counts.set(fam, (counts.get(fam) ?? 0) + 1);
	}

	return {
		slug,
		label: WX_CATALOG_PRODUCT_LABELS[slug],
		tokenFamilies: productRaw.tokenFamilies.map((f) => ({
			slug: f.slug,
			label: f.label,
			decode: f.decode,
			references: f.references.map((r) => ({ source: r.source, detail: r.detail })),
			exampleCount: counts.get(f.slug) ?? 0,
		})),
		examples: productRaw.examples.map((e) => ({
			slug: e.slug,
			raw: e.raw,
			tokenFamilies: [...e.tokenFamilies],
			synoptic: e.synoptic,
			triageDrivers: [...e.triageDrivers],
			references: e.references.map((r) => ({ source: r.source, detail: r.detail })),
		})),
	};
}
