/**
 * Regenerate `libs/aviation/src/references/aviation.ts` from a
 * `Reference[]` snapshot.
 *
 * Why this file exists at all (decision 2026-04-24, user): `AVIATION_REFERENCES`
 * is imported by universal `+page.ts` loads in study. Those run in both
 * server and client after hydration. TOML cannot be parsed in the browser
 * without shipping a TOML library to the client bundle, which regresses
 * client-nav perf. Option 3 keeps the TS artifact generated; authoritative
 * edits flow TOML -> hangar sync -> regenerate this file + commit.
 *
 * Determinism contract:
 *   - References are emitted in id-ascending order (same as `encodeReferences`).
 *   - Field order inside a reference is fixed.
 *   - The file is idempotent: calling `emitAviationTs` on the same input
 *     twice returns identical strings.
 *   - Optional fields (`author`, `reviewedAt`, `verbatim`, `tags.phaseOfFlight`,
 *     `tags.certApplicability`, `tags.keywords`) are emitted only when present.
 *
 * Consumer contract: exports `AVIATION_REFERENCES: readonly Reference[]` and
 * calls `registerReferences(AVIATION_REFERENCES)` at module load (matches the
 * shape consumers imported before the TOML migration).
 */

import type { Reference, SourceCitation, VerbatimBlock } from '@ab/aviation';

/** Header banner prefixed to every emitted aviation.ts body. */
const HEADER = [
	'/**',
	' * AVIATION_REFERENCES -- generated by @ab/hangar-sync.',
	' *',
	' * DO NOT EDIT BY HAND. Authoritative edits happen via the hangar',
	' * `/glossary` UI; the sync job writes the TOML seed and regenerates',
	' * this file in the same commit. Manual edits here will be clobbered by',
	' * the next sync.',
	' *',
	' * Field order + optional-field presence are deterministic so the file',
	' * diffs cleanly. To add a field, update the emit script, not this',
	' * file.',
	' */',
	'',
	"import { registerReferences } from '../registry';",
	"import type { Reference } from '../schema/reference';",
	'',
].join('\n');

const INDENT = '\t';

/**
 * JavaScript string literal -- single-quoted, escaping backslashes, quotes,
 * and control characters. We never emit template literals because they mask
 * diffs across line-break changes.
 */
function formatString(value: string): string {
	let out = "'";
	for (const ch of value) {
		const code = ch.codePointAt(0) ?? 0;
		if (ch === "'") out += "\\'";
		else if (ch === '\\') out += '\\\\';
		else if (ch === '\n') out += '\\n';
		else if (ch === '\r') out += '\\r';
		else if (ch === '\t') out += '\\t';
		else if (code < 0x20 || code === 0x7f) {
			out += `\\u${code.toString(16).padStart(4, '0')}`;
		} else {
			out += ch;
		}
	}
	out += "'";
	return out;
}

function formatStringArray(values: readonly string[], indent: string): string {
	if (values.length === 0) return '[]';
	const inner = values.map((v) => `${indent}${INDENT}${formatString(v)},`).join('\n');
	return `[\n${inner}\n${indent}]`;
}

function formatLocator(locator: Readonly<Record<string, string | number>>, indent: string): string {
	const keys = Object.keys(locator);
	if (keys.length === 0) return '{}';
	// Preserve insertion order of the input; citation locators are
	// source-type specific and order-meaningful to human readers.
	const inner = keys
		.map((k) => {
			const v = locator[k];
			const formatted = typeof v === 'number' ? `${v}` : formatString(v);
			return `${indent}${INDENT}${k}: ${formatted},`;
		})
		.join('\n');
	return `{\n${inner}\n${indent}}`;
}

function formatCitation(citation: SourceCitation, indent: string): string {
	const lines: string[] = [];
	const inner = `${indent}${INDENT}`;
	lines.push(`${indent}{`);
	lines.push(`${inner}sourceId: ${formatString(citation.sourceId)},`);
	lines.push(`${inner}locator: ${formatLocator(citation.locator, inner)},`);
	if (citation.url !== undefined) {
		lines.push(`${inner}url: ${formatString(citation.url)},`);
	}
	lines.push(`${indent}},`);
	return lines.join('\n');
}

function formatCitations(citations: readonly SourceCitation[], indent: string): string {
	if (citations.length === 0) return '[]';
	const body = citations.map((c) => formatCitation(c, `${indent}${INDENT}`)).join('\n');
	return `[\n${body}\n${indent}]`;
}

function formatTags(tags: Reference['tags'], indent: string): string {
	const inner = `${indent}${INDENT}`;
	const lines: string[] = [];
	lines.push(`${indent}{`);
	lines.push(`${inner}sourceType: ${formatString(tags.sourceType)},`);
	lines.push(`${inner}aviationTopic: ${formatStringArray(tags.aviationTopic, inner)},`);
	lines.push(`${inner}flightRules: ${formatString(tags.flightRules)},`);
	lines.push(`${inner}knowledgeKind: ${formatString(tags.knowledgeKind)},`);
	if (tags.phaseOfFlight !== undefined) {
		lines.push(`${inner}phaseOfFlight: ${formatStringArray(tags.phaseOfFlight, inner)},`);
	}
	if (tags.certApplicability !== undefined) {
		lines.push(`${inner}certApplicability: ${formatStringArray(tags.certApplicability, inner)},`);
	}
	if (tags.keywords !== undefined) {
		lines.push(`${inner}keywords: ${formatStringArray(tags.keywords, inner)},`);
	}
	lines.push(`${indent}},`);
	return lines.join('\n');
}

function formatVerbatim(verbatim: VerbatimBlock, indent: string): string {
	const inner = `${indent}${INDENT}`;
	const lines: string[] = [];
	lines.push(`${indent}{`);
	lines.push(`${inner}text: ${formatString(verbatim.text)},`);
	lines.push(`${inner}sourceVersion: ${formatString(verbatim.sourceVersion)},`);
	lines.push(`${inner}extractedAt: ${formatString(verbatim.extractedAt)},`);
	lines.push(`${indent}},`);
	return lines.join('\n');
}

function formatReference(reference: Reference): string {
	// Top-level references sit inside the array literal with one-tab indent.
	const indent = INDENT;
	const inner = `${indent}${INDENT}`;
	const lines: string[] = [];
	lines.push(`${indent}{`);
	lines.push(`${inner}id: ${formatString(reference.id)},`);
	lines.push(`${inner}displayName: ${formatString(reference.displayName)},`);
	lines.push(`${inner}aliases: ${formatStringArray(reference.aliases, inner)},`);
	lines.push(`${inner}paraphrase: ${formatString(reference.paraphrase)},`);
	lines.push(`${inner}tags: ${formatTags(reference.tags, inner)}`);
	lines.push(`${inner}sources: ${formatCitations(reference.sources, inner)},`);
	lines.push(`${inner}related: ${formatStringArray(reference.related, inner)},`);
	if (reference.author !== undefined) {
		lines.push(`${inner}author: ${formatString(reference.author)},`);
	}
	if (reference.reviewedAt !== undefined) {
		lines.push(`${inner}reviewedAt: ${formatString(reference.reviewedAt)},`);
	}
	if (reference.verbatim !== undefined) {
		lines.push(`${inner}verbatim: ${formatVerbatim(reference.verbatim, inner)}`);
	}
	lines.push(`${indent}},`);
	return lines.join('\n');
}

/**
 * Emit the full aviation.ts body for `references`. References are sorted by
 * id ascending so the emitted file is deterministic regardless of input
 * order.
 */
export function emitAviationTs(references: readonly Reference[]): string {
	const sorted = [...references].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
	const body = sorted.map(formatReference).join('\n');
	return [
		HEADER,
		'export const AVIATION_REFERENCES: readonly Reference[] = [',
		body,
		'];',
		'',
		'// Register at module load so the registry is populated before any consumer',
		'// imports it.',
		'registerReferences(AVIATION_REFERENCES);',
		'',
	].join('\n');
}
