#!/usr/bin/env bun
/**
 * test-lint -- CLI entry.
 *
 * Scans `libs/**\/*.test.ts`, `libs/**\/*.svelte.test.ts`, `apps/**\/*.test.ts`,
 * `apps/**\/*.svelte.test.ts` for weak/redundant assertion patterns. Reports
 * a non-zero exit when a new (un-ignored) violation appears.
 *
 * Ignore file: `tools/test-lint/ignore.txt`. Each non-blank, non-comment line
 * is `<relative-path>:<line>:<rule>` and suppresses one known site. The
 * existing 89 sites are grandfathered; new occurrences are blocked.
 *
 * Usage:
 *   bun tools/test-lint/bin.ts              # lint current tree
 *   bun tools/test-lint/bin.ts --fix-ignore # rewrite ignore.txt with current findings
 *   bun tools/test-lint/bin.ts --json       # machine-readable output
 */

import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';

const REPO_ROOT = resolve(import.meta.dir, '..', '..');
const IGNORE_PATH = join(REPO_ROOT, 'tools', 'test-lint', 'ignore.txt');

const DEFAULT_ROOTS = ['libs', 'apps'];
const EXCLUDE_PATHS = ['node_modules', '.svelte-kit', 'dist', 'build', 'tools/test-lint'];

const TEST_FILE_RE = /\.(test|svelte\.test)\.ts$/;

interface Violation {
	relativePath: string;
	line: number;
	rule: string;
	context: string;
}

interface Rule {
	id: string;
	pattern: RegExp;
	description: string;
}

const RULES: readonly Rule[] = [
	{
		id: 'no-toBeTruthy-on-existence',
		// Match `.toBeTruthy()` directly. We could narrow to `expect(...)` chains
		// but the false-positive rate is near zero -- tests rarely use the
		// matcher in any other context.
		pattern: /\.toBeTruthy\(\)/,
		description:
			'.toBeTruthy() is redundant on testing-library queries (which throw on miss) and a tautology on string/object values. Prefer .toBeInTheDocument(), .toMatch(/.../), .toMatchObject({...}), or .toBe(true). See tools/test-lint/README.md.',
	},
];

async function* walk(dir: string): AsyncGenerator<string> {
	let entries;
	try {
		entries = await readdir(dir, { withFileTypes: true });
	} catch {
		return;
	}
	for (const entry of entries) {
		const full = join(dir, entry.name);
		const rel = relative(REPO_ROOT, full);
		if (EXCLUDE_PATHS.some((ex) => rel.startsWith(ex))) continue;
		if (entry.isDirectory()) {
			yield* walk(full);
		} else if (entry.isFile() && TEST_FILE_RE.test(entry.name)) {
			yield full;
		}
	}
}

async function scanFile(absPath: string): Promise<readonly Violation[]> {
	const source = await readFile(absPath, 'utf-8');
	const relativePath = relative(REPO_ROOT, absPath);
	const out: Violation[] = [];
	const lines = source.split('\n');
	for (let i = 0; i < lines.length; i += 1) {
		const line = lines[i] ?? '';
		for (const rule of RULES) {
			if (rule.pattern.test(line)) {
				out.push({ relativePath, line: i + 1, rule: rule.id, context: line.trim() });
			}
		}
	}
	return out;
}

interface Ignore {
	relativePath: string;
	line: number;
	rule: string;
}

async function loadIgnores(): Promise<readonly Ignore[]> {
	let raw: string;
	try {
		raw = await readFile(IGNORE_PATH, 'utf-8');
	} catch {
		return [];
	}
	const out: Ignore[] = [];
	for (const rawLine of raw.split('\n')) {
		const line = rawLine.trim();
		if (line === '' || line.startsWith('#')) continue;
		const parts = line.split(':');
		if (parts.length !== 3) continue;
		const [path, lineStr, rule] = parts;
		if (path === undefined || lineStr === undefined || rule === undefined) continue;
		const lineNum = Number.parseInt(lineStr, 10);
		if (Number.isNaN(lineNum)) continue;
		out.push({ relativePath: path, line: lineNum, rule });
	}
	return out;
}

function ignoreKey(v: { relativePath: string; line: number; rule: string }): string {
	return `${v.relativePath}:${v.line}:${v.rule}`;
}

async function writeIgnoreFile(violations: readonly Violation[]): Promise<void> {
	const sorted = [...violations].sort((a, b) =>
		a.relativePath !== b.relativePath ? a.relativePath.localeCompare(b.relativePath) : a.line - b.line,
	);
	const header =
		'# test-lint grandfather list -- one ignore per line: <path>:<line>:<rule>\n' +
		'# Generated by `bun tools/test-lint/bin.ts --fix-ignore`. When you touch\n' +
		'# a file with an ignore here, fix the violation; do not re-add the ignore.\n' +
		'# See tools/test-lint/README.md for replacement patterns.\n\n';
	const body = sorted.map((v) => ignoreKey(v)).join('\n');
	await writeFile(IGNORE_PATH, header + body + '\n', 'utf-8');
}

async function main(): Promise<void> {
	const args = process.argv.slice(2);
	const fixIgnore = args.includes('--fix-ignore');
	const json = args.includes('--json');
	const roots = args.filter((a) => !a.startsWith('--'));
	const targetRoots = roots.length > 0 ? roots : DEFAULT_ROOTS;

	const allViolations: Violation[] = [];
	for (const root of targetRoots) {
		const absRoot = resolve(REPO_ROOT, root);
		try {
			await stat(absRoot);
		} catch {
			continue;
		}
		for await (const file of walk(absRoot)) {
			const fileViolations = await scanFile(file);
			allViolations.push(...fileViolations);
		}
	}

	if (fixIgnore) {
		await writeIgnoreFile(allViolations);
		console.log(`test-lint: wrote ${allViolations.length} ignores to ${relative(REPO_ROOT, IGNORE_PATH)}`);
		return;
	}

	const ignores = await loadIgnores();
	const ignoreSet = new Set(ignores.map(ignoreKey));
	const unsuppressed = allViolations.filter((v) => !ignoreSet.has(ignoreKey(v)));
	const suppressed = allViolations.length - unsuppressed.length;

	if (json) {
		console.log(JSON.stringify({ violations: unsuppressed, suppressed, total: allViolations.length }, null, 2));
		process.exit(unsuppressed.length === 0 ? 0 : 1);
	}

	if (unsuppressed.length === 0) {
		console.log(`test-lint: clean (${suppressed} grandfathered, ${allViolations.length} total)`);
		process.exit(0);
	}

	console.error(`test-lint: ${unsuppressed.length} new violation(s) (plus ${suppressed} grandfathered):`);
	for (const v of unsuppressed) {
		console.error(`  ${v.relativePath}:${v.line}  [${v.rule}]`);
		console.error(`    ${v.context}`);
	}
	console.error('');
	console.error('To fix: see tools/test-lint/README.md for replacement patterns.');
	console.error('To grandfather (only for legacy code being deliberately frozen):');
	console.error('  bun tools/test-lint/bin.ts --fix-ignore');
	process.exit(1);
}

main().catch((err) => {
	console.error(err);
	process.exit(2);
});
