#!/usr/bin/env bun
/**
 * Generate aggregator views from work-package frontmatter. ADR 025, Phase 4.
 *
 * Reads every `docs/work-packages/<slug>/spec.md` via the WP loader, then
 * emits three families of artifacts:
 *
 *   1. `docs/work/BOARD.md`              -- global WP board, all WPs
 *   2. `docs/products/<product>/ROADMAP.md`
 *                                        -- one per real product surface
 *   3. `docs/work/SHIPPED.md`            -- reverse-chrono shipped log
 *
 * Each file starts with a DO NOT EDIT sentinel; the `tracking-generate` step
 * in `bun run check` re-runs this generator and fails if the result diverges
 * from what's on disk (catches both hand edits and stale generator runs).
 *
 * Output is deterministic across runs:
 *   - WPs are grouped by status using a fixed enum order
 *   - within each section, WPs sort alphabetically by id
 *
 * The build timestamp is NOT written into committed files (it would churn on
 * every run). It is recorded in a sidecar at `.cache/check/tracking-generate.timestamp`.
 *
 * Modes:
 *   bun scripts/tracking/generate.ts              # write files in place
 *   bun scripts/tracking/generate.ts --check      # exit 1 if files differ from generated
 *   bun scripts/tracking/generate.ts --all        # SHIPPED.md emits all entries (default 90d)
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import type { WPProduct, WPStatus } from '@ab/constants';
import type { WorkPackage, WorkPackageFrontmatter } from '@ab/types';
import { loadAllWorkPackages } from '../lib/wp-loader';

// ---------------------------------------------------------------------------
// Constants and types
// ---------------------------------------------------------------------------

/** Real product surfaces that get a ROADMAP.md generated. The `WPProduct`
 * type constrains every entry to a valid product slug, so a typo here is a
 * compile error. Excludes:
 *   - `course`   (content corpus, not a product)
 *   - `platform` (cross-cutting infra, not a product)
 *   - `none`     (escape hatch for cross-cutting work)
 */
export const ROADMAP_PRODUCTS: readonly WPProduct[] = ['study', 'hangar', 'sim', 'flightbag', 'avionics'] as const;

/** Path to the shipped-log sidecar timestamp (avoids churning committed files). */
const TIMESTAMP_SIDECAR = '.cache/check/tracking-generate.timestamp';

/** Sentinel comment that opens every generated file. The lint that wraps this
 * generator (the `tracking-generate` step in `bun run check`) re-runs the
 * generator into memory and diffs against on-disk files; any hand edit therefore
 * fails check. The sentinel is a human-facing reminder, not the enforcement. */
export const SENTINEL = '<!-- DO NOT EDIT - generated by scripts/tracking/generate.ts -->';

/** Status-section ordering. WPs whose frontmatter is invalid (loader returned
 * null frontmatter) are surfaced under a synthetic `invalid` section so the
 * board doesn't quietly drop them. */
export const BOARD_SECTIONS = [
	'in-flight',
	'signed-off',
	'shipped',
	'draft',
	'abandoned',
	'superseded',
	'invalid',
] as const;
export type BoardSection = (typeof BOARD_SECTIONS)[number];

const SECTION_HEADINGS: Record<BoardSection, string> = {
	'in-flight': 'In flight',
	'signed-off': 'Signed off',
	shipped: 'Shipped',
	draft: 'Draft',
	abandoned: 'Abandoned',
	superseded: 'Superseded',
	invalid: 'Invalid (frontmatter errors)',
};

/** Default cap for SHIPPED.md when --all is not passed. */
export const SHIPPED_DEFAULT_DAYS = 90;
/** Group-by-month threshold. Above this, SHIPPED.md groups by year-month. */
export const SHIPPED_GROUP_THRESHOLD = 20;

/** GitHub repo root used for `shipped_prs` links. */
const GITHUB_REPO_URL = 'https://github.com/joshball/airboss';

/** Output paths, all relative to repo root. */
export const BOARD_REL = 'docs/work/BOARD.md';
export const SHIPPED_REL = 'docs/work/SHIPPED.md';
export function roadmapRel(product: WPProduct): string {
	return `docs/products/${product}/ROADMAP.md`;
}

// ---------------------------------------------------------------------------
// CLI parsing
// ---------------------------------------------------------------------------

interface CliArgs {
	check: boolean;
	all: boolean;
}

function parseArgs(argv: readonly string[]): CliArgs {
	const args: CliArgs = { check: false, all: false };
	for (const a of argv) {
		if (a === '--check') args.check = true;
		else if (a === '--all') args.all = true;
		else if (a === '--help' || a === '-h') {
			printHelp();
			process.exit(0);
		} else {
			console.error(`tracking/generate: unknown flag "${a}"`);
			printHelp();
			process.exit(1);
		}
	}
	return args;
}

function printHelp(): void {
	console.log('Usage: bun scripts/tracking/generate.ts [flags]');
	console.log('');
	console.log('Flags:');
	console.log('  --check     Report drift without writing. Exit 1 if any generated file differs.');
	console.log('  --all       SHIPPED.md emits every entry instead of the last 90 days.');
	console.log('  --help, -h  Show this help.');
}

// ---------------------------------------------------------------------------
// Repo root resolution
// ---------------------------------------------------------------------------

function resolveRepoRoot(): string {
	let dir = import.meta.dir;
	for (let i = 0; i < 16; i += 1) {
		const candidate = join(dir, 'package.json');
		try {
			const json = JSON.parse(readFileSync(candidate, 'utf8')) as { name?: string };
			if (json.name === 'airboss') return dir;
		} catch {
			/* keep walking */
		}
		const parent = resolve(dir, '..');
		if (parent === dir) break;
		dir = parent;
	}
	throw new Error('tracking/generate: unable to locate repo root');
}

// ---------------------------------------------------------------------------
// Sorting + grouping helpers
// ---------------------------------------------------------------------------

interface ClassifiedPackage {
	wp: WorkPackage;
	section: BoardSection;
}

function classify(wp: WorkPackage): ClassifiedPackage {
	if (wp.frontmatter === null) return { wp, section: 'invalid' };
	const status: WPStatus = wp.frontmatter.status;
	// status is a WP_STATUSES enum value, all of which are also BoardSection
	// values (BoardSection adds the synthetic `invalid`).
	return { wp, section: status as BoardSection };
}

function compareById(a: WorkPackage, b: WorkPackage): number {
	if (a.id < b.id) return -1;
	if (a.id > b.id) return 1;
	return 0;
}

interface SectionGroup {
	section: BoardSection;
	heading: string;
	packages: WorkPackage[];
}

function groupBySection(packages: readonly WorkPackage[]): SectionGroup[] {
	const buckets = new Map<BoardSection, WorkPackage[]>();
	for (const wp of packages) {
		const c = classify(wp);
		const arr = buckets.get(c.section) ?? [];
		arr.push(wp);
		buckets.set(c.section, arr);
	}
	const groups: SectionGroup[] = [];
	for (const section of BOARD_SECTIONS) {
		const arr = buckets.get(section) ?? [];
		arr.sort(compareById);
		if (arr.length === 0) continue;
		groups.push({ section, heading: SECTION_HEADINGS[section], packages: arr });
	}
	return groups;
}

// ---------------------------------------------------------------------------
// Markdown rendering helpers
// ---------------------------------------------------------------------------

function escapePipe(s: string): string {
	return s.replace(/\|/g, '\\|');
}

/** Compute a POSIX-style relative path. We always emit forward slashes so the
 * generated markdown is portable across Unix and Windows checkouts. */
function relativePosix(fromDir: string, to: string): string {
	const result = relative(fromDir, to);
	return result.split('\\').join('/');
}

/** Produce a `[text](relative-path)` link from a generated file to a
 * `spec.md`. Both `specPathRel` and `outputFileRel` are repo-root relative. */
function renderSpecLink(text: string, specPathRel: string, outputFileRel: string): string {
	const fromDir = dirname(outputFileRel);
	const rel = relativePosix(fromDir, specPathRel);
	return `[${escapePipe(text)}](${rel})`;
}

interface BoardRow {
	id: string;
	title: string;
	product: string;
	category: string;
	agentReview: string;
	humanReview: string;
	specPathRel: string;
}

function rowFromWp(wp: WorkPackage, repoRoot: string): BoardRow {
	const fm = wp.frontmatter;
	const specRel = relative(repoRoot, wp.specPath).split('\\').join('/');
	if (fm === null) {
		return {
			id: wp.id,
			title: `(${wp.validation_errors.length} validation errors)`,
			product: '?',
			category: '?',
			agentReview: '?',
			humanReview: '?',
			specPathRel: specRel,
		};
	}
	return {
		id: wp.id,
		title: fm.title,
		product: fm.product,
		category: fm.category,
		agentReview: fm.agent_review_status,
		humanReview: fm.human_review_status,
		specPathRel: specRel,
	};
}

function renderBoardTable(rows: readonly BoardRow[], outputFileRel: string): string {
	if (rows.length === 0) return '';
	const headers: readonly string[] = ['ID', 'Title', 'Product', 'Category', 'Agent review', 'Human review'];
	const cells: string[][] = rows.map((r) => [
		renderSpecLink(r.id, r.specPathRel, outputFileRel),
		escapePipe(r.title),
		r.product,
		r.category,
		r.agentReview,
		r.humanReview,
	]);
	const widths = headers.map((h, i) => {
		let w = h.length;
		for (const row of cells) {
			const v = row[i] ?? '';
			if (v.length > w) w = v.length;
		}
		return w < 2 ? 2 : w;
	});
	const lines: string[] = [];
	lines.push(`| ${headers.map((h, i) => h.padEnd(widths[i] ?? 0)).join(' | ')} |`);
	lines.push(`| ${widths.map((w) => '-'.repeat(w)).join(' | ')} |`);
	for (const row of cells) {
		lines.push(`| ${row.map((v, i) => v.padEnd(widths[i] ?? 0)).join(' | ')} |`);
	}
	return lines.join('\n');
}

function renderBoardSections(groups: readonly SectionGroup[], outputFileRel: string, repoRoot: string): string[] {
	const out: string[] = [];
	for (const group of groups) {
		out.push('');
		out.push(`## ${group.heading} (${group.packages.length})`);
		out.push('');
		const rows = group.packages.map((wp) => rowFromWp(wp, repoRoot));
		out.push(renderBoardTable(rows, outputFileRel));
	}
	return out;
}

// ---------------------------------------------------------------------------
// BOARD.md
// ---------------------------------------------------------------------------

function renderBoard(packages: readonly WorkPackage[], repoRoot: string): string {
	const groups = groupBySection(packages);
	const lines: string[] = [];
	lines.push(SENTINEL);
	lines.push('');
	lines.push('# Work package board');
	lines.push('');
	lines.push('> Generated by `bun scripts/tracking/generate.ts`. DO NOT EDIT.');
	lines.push('>');
	lines.push(`> Total work packages: ${packages.length}.`);
	lines.push('');
	lines.push('Aggregated view of every `docs/work-packages/<slug>/spec.md` frontmatter.');
	lines.push('Sections sort by status; within each section WPs sort alphabetically by id.');
	if (packages.length === 0) {
		lines.push('');
		lines.push('_No work packages found._');
		lines.push('');
		return finalizeOutput(lines);
	}
	lines.push(...renderBoardSections(groups, BOARD_REL, repoRoot));
	return finalizeOutput(lines);
}

// ---------------------------------------------------------------------------
// ROADMAP.md (per product)
// ---------------------------------------------------------------------------

function productHeading(product: WPProduct): string {
	switch (product) {
		case 'study':
			return 'Study';
		case 'hangar':
			return 'Hangar';
		case 'sim':
			return 'Sim';
		case 'flightbag':
			return 'Flightbag';
		case 'avionics':
			return 'Avionics';
		default:
			return product;
	}
}

function renderRoadmap(product: WPProduct, packages: readonly WorkPackage[], repoRoot: string): string {
	const filtered = packages.filter((wp) => wp.frontmatter !== null && wp.frontmatter.product === product);
	const groups = groupBySection(filtered);
	const lines: string[] = [];
	lines.push(SENTINEL);
	lines.push('');
	lines.push(`# ${productHeading(product)} -- Roadmap`);
	lines.push('');
	lines.push('> Generated by `bun scripts/tracking/generate.ts`. DO NOT EDIT.');
	lines.push('>');
	lines.push(`> Filtered to \`product: ${product}\`. Total: ${filtered.length}.`);
	lines.push('');
	lines.push(`Work packages targeting the \`${product}\` surface, grouped by status.`);
	lines.push('Within each section WPs sort alphabetically by id.');
	if (filtered.length === 0) {
		lines.push('');
		lines.push(`_No work packages currently target \`${product}\`._`);
		return finalizeOutput(lines);
	}
	lines.push(...renderBoardSections(groups, roadmapRel(product), repoRoot));
	return finalizeOutput(lines);
}

// ---------------------------------------------------------------------------
// SHIPPED.md
// ---------------------------------------------------------------------------

interface ShippedEntry {
	wp: WorkPackage;
	frontmatter: WorkPackageFrontmatter;
	shippedDate: string;
}

function collectShipped(packages: readonly WorkPackage[]): ShippedEntry[] {
	const entries: ShippedEntry[] = [];
	for (const wp of packages) {
		const fm = wp.frontmatter;
		if (fm === null) continue;
		if (fm.status !== 'shipped') continue;
		if (fm.shipped_date === undefined || fm.shipped_date === null) continue;
		entries.push({ wp, frontmatter: fm, shippedDate: fm.shipped_date });
	}
	// Reverse-chrono by shipped_date, ties broken by id ascending for stability.
	entries.sort((a, b) => {
		if (a.shippedDate > b.shippedDate) return -1;
		if (a.shippedDate < b.shippedDate) return 1;
		if (a.wp.id < b.wp.id) return -1;
		if (a.wp.id > b.wp.id) return 1;
		return 0;
	});
	return entries;
}

function filterByDays(entries: readonly ShippedEntry[], days: number, today: Date): ShippedEntry[] {
	if (entries.length === 0) return [];
	const cutoff = new Date(today.getTime());
	cutoff.setUTCDate(cutoff.getUTCDate() - days);
	const cutoffIso = cutoff.toISOString().slice(0, 10);
	return entries.filter((e) => e.shippedDate >= cutoffIso);
}

function renderShippedTable(entries: readonly ShippedEntry[], outputFileRel: string, repoRoot: string): string {
	if (entries.length === 0) return '';
	type Cells = readonly [string, string, string, string];
	const headers: Cells = ['ID', 'Title', 'Shipped', 'PRs'];
	const cells: Cells[] = entries.map((entry) => {
		const { wp, frontmatter } = entry;
		const specRel = relative(repoRoot, wp.specPath).split('\\').join('/');
		const id = renderSpecLink(wp.id, specRel, outputFileRel);
		const title = escapePipe(frontmatter.title);
		const date = entry.shippedDate;
		const prs =
			frontmatter.shipped_prs.length === 0
				? '-'
				: frontmatter.shipped_prs.map((pr) => `[#${pr}](${GITHUB_REPO_URL}/pull/${pr})`).join(', ');
		return [id, title, date, prs] as const;
	});
	const widths = headers.map((h, i) => {
		let w = h.length;
		for (const row of cells) {
			const v = row[i] ?? '';
			if (v.length > w) w = v.length;
		}
		return w < 2 ? 2 : w;
	});
	const lines: string[] = [];
	lines.push(`| ${headers.map((h, i) => h.padEnd(widths[i] ?? 0)).join(' | ')} |`);
	lines.push(`| ${widths.map((w) => '-'.repeat(w)).join(' | ')} |`);
	for (const row of cells) {
		lines.push(`| ${row.map((v, i) => v.padEnd(widths[i] ?? 0)).join(' | ')} |`);
	}
	return lines.join('\n');
}

interface MonthGroup {
	label: string;
	entries: ShippedEntry[];
}

function groupByMonth(entries: readonly ShippedEntry[]): MonthGroup[] {
	const map = new Map<string, ShippedEntry[]>();
	const order: string[] = [];
	for (const entry of entries) {
		const month = entry.shippedDate.slice(0, 7);
		const arr = map.get(month);
		if (arr === undefined) {
			map.set(month, [entry]);
			order.push(month);
		} else {
			arr.push(entry);
		}
	}
	return order.map((label) => ({ label, entries: map.get(label) ?? [] }));
}

interface RenderShippedOptions {
	all: boolean;
	today: Date;
	repoRoot: string;
}

function renderShipped(packages: readonly WorkPackage[], opts: RenderShippedOptions): string {
	const allEntries = collectShipped(packages);
	const entries = opts.all ? allEntries : filterByDays(allEntries, SHIPPED_DEFAULT_DAYS, opts.today);
	const lines: string[] = [];
	lines.push(SENTINEL);
	lines.push('');
	lines.push('# Shipped log');
	lines.push('');
	lines.push('> Generated by `bun scripts/tracking/generate.ts`. DO NOT EDIT.');
	lines.push('>');
	const scopeNote = opts.all
		? `> Scope: every shipped work package (${entries.length} total).`
		: `> Scope: last ${SHIPPED_DEFAULT_DAYS} days (${entries.length} of ${allEntries.length} total). Use \`--all\` for the full log.`;
	lines.push(scopeNote);
	lines.push('');
	lines.push('Reverse-chronological list of work packages whose `status` is `shipped`.');
	lines.push('Each entry links to its `spec.md` and the PR(s) that closed it.');
	if (entries.length === 0) {
		lines.push('');
		lines.push('_No shipped work packages in scope yet._');
		return finalizeOutput(lines);
	}
	if (entries.length > SHIPPED_GROUP_THRESHOLD) {
		const monthGroups = groupByMonth(entries);
		for (const group of monthGroups) {
			lines.push('');
			lines.push(`## ${group.label} (${group.entries.length})`);
			lines.push('');
			lines.push(renderShippedTable(group.entries, SHIPPED_REL, opts.repoRoot));
		}
	} else {
		lines.push('');
		lines.push(renderShippedTable(entries, SHIPPED_REL, opts.repoRoot));
	}
	return finalizeOutput(lines);
}

// ---------------------------------------------------------------------------
// Output finalize
// ---------------------------------------------------------------------------

function finalizeOutput(lines: readonly string[]): string {
	// Trim trailing blank lines, then append exactly one newline at EOF.
	const joined = lines.join('\n').replace(/\n+$/, '');
	return `${joined}\n`;
}

// ---------------------------------------------------------------------------
// Generation entry point
// ---------------------------------------------------------------------------

export interface GeneratedFile {
	relPath: string;
	content: string;
}

export interface GenerateOptions {
	all?: boolean;
	today?: Date;
	repoRoot?: string;
}

/** Pure: turn a list of work packages into the full set of generated files.
 * Exported so tests can call it without writing to disk. The `repoRoot` is
 * used to resolve `wp.specPath` to a relative link target; pass the same root
 * the loader was called with. */
export function generateAll(packages: readonly WorkPackage[], opts: GenerateOptions = {}): GeneratedFile[] {
	const all = opts.all ?? false;
	const today = opts.today ?? new Date();
	const repoRoot = opts.repoRoot ?? resolveRepoRoot();
	const files: GeneratedFile[] = [];
	files.push({ relPath: BOARD_REL, content: renderBoard(packages, repoRoot) });
	for (const product of ROADMAP_PRODUCTS) {
		files.push({ relPath: roadmapRel(product), content: renderRoadmap(product, packages, repoRoot) });
	}
	files.push({
		relPath: SHIPPED_REL,
		content: renderShipped(packages, { all, today, repoRoot }),
	});
	return files;
}

// ---------------------------------------------------------------------------
// File IO
// ---------------------------------------------------------------------------

function writeFiles(files: readonly GeneratedFile[], repoRoot: string): void {
	for (const file of files) {
		const abs = join(repoRoot, file.relPath);
		mkdirSync(dirname(abs), { recursive: true });
		writeFileSync(abs, file.content);
	}
	// Sidecar timestamp -- not committed (`.cache/` is gitignored).
	const sidecar = join(repoRoot, TIMESTAMP_SIDECAR);
	try {
		mkdirSync(dirname(sidecar), { recursive: true });
		writeFileSync(sidecar, `${new Date().toISOString()}\n`);
	} catch {
		/* best effort */
	}
}

interface DriftEntry {
	relPath: string;
	missing: boolean;
}

function diffFiles(files: readonly GeneratedFile[], repoRoot: string): DriftEntry[] {
	const drift: DriftEntry[] = [];
	for (const file of files) {
		const abs = join(repoRoot, file.relPath);
		let actual: string | null = null;
		try {
			actual = readFileSync(abs, 'utf8');
		} catch {
			actual = null;
		}
		if (actual !== file.content) {
			drift.push({ relPath: file.relPath, missing: actual === null });
		}
	}
	return drift;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<number> {
	const args = parseArgs(process.argv.slice(2));
	const repoRoot = resolveRepoRoot();
	const packages = loadAllWorkPackages(repoRoot);
	const files = generateAll(packages, { all: args.all, repoRoot });

	if (args.check) {
		const drift = diffFiles(files, repoRoot);
		if (drift.length === 0) {
			console.log(`tracking-generate: ${files.length} file(s) up to date.`);
			return 0;
		}
		console.error(`tracking-generate: ${drift.length} file(s) out of date:`);
		for (const d of drift) {
			console.error(`  - ${d.relPath}${d.missing ? ' (missing on disk)' : ''}`);
		}
		console.error('');
		console.error('Run `bun run tracking:generate` to refresh.');
		return 1;
	}

	writeFiles(files, repoRoot);
	console.log(`tracking-generate: wrote ${files.length} file(s).`);
	for (const f of files) console.log(`  - ${f.relPath}`);
	return 0;
}

// Bun runs this file as a script when invoked directly. Skip the main() call
// when imported by tests.
if (import.meta.main) {
	const exitCode = await main();
	process.exit(exitCode);
}
