/**
 * Bugs index generator. Phase 6 of `tracking-system-overhaul`.
 *
 * Renders `docs/bugs/INDEX.md`: open bugs grouped by product, then by
 * severity within each product. The Phase 4 generator (parallel WP) can
 * absorb this surface later by importing `generateBugsIndex` and emitting
 * its output as one section of a larger composite index.
 *
 * Pure function over `Bug[]` so tests can pass synthetic input. The
 * `bun run bug index` driver in `scripts/bug.ts` wires this to disk.
 */

import { BUG_SEVERITIES, type BugSeverity, WP_PRODUCTS, type WPProduct } from '@ab/constants';
import type { Bug } from '@ab/types';

const PRODUCT_LABELS: Record<WPProduct, string> = {
	study: 'Study',
	hangar: 'Hangar',
	sim: 'Sim',
	flightbag: 'Flightbag',
	avionics: 'Avionics',
	platform: 'Platform',
	course: 'Course',
	none: 'No product',
};

const SEVERITY_LABELS: Record<BugSeverity, string> = {
	blocking: 'Blocking',
	major: 'Major',
	minor: 'Minor',
	nit: 'Nit',
};

interface OpenBugRow {
	id: string;
	severity: BugSeverity;
	title: string;
	product: WPProduct;
	discovered_pr: number | null;
}

function asOpenRow(bug: Bug): OpenBugRow | null {
	const fm = bug.frontmatter;
	if (fm === null) return null;
	if (fm.status !== 'open') return null;
	return {
		id: bug.id,
		severity: fm.severity,
		title: fm.title,
		product: fm.product,
		discovered_pr: fm.discovered_pr ?? null,
	};
}

function severityOrder(s: BugSeverity): number {
	return BUG_SEVERITIES.indexOf(s);
}

function productOrder(p: WPProduct): number {
	return WP_PRODUCTS.indexOf(p);
}

/**
 * Render the full INDEX.md body. Pure: no IO. Caller writes to disk.
 *
 * Layout:
 *
 *   # Bugs
 *
 *   N open bugs of M total. Closed bugs (fixed / wontfix / duplicate)
 *   are kept on disk for history but excluded from this index.
 *
 *   ## Per-product
 *
 *   ### {Product} (open: K)
 *
 *   #### Blocking
 *
 *   - [bug-id](bug-id.md) -- title (PR #N)
 */
export function generateBugsIndex(bugs: readonly Bug[]): string {
	const open: OpenBugRow[] = [];
	for (const bug of bugs) {
		const row = asOpenRow(bug);
		if (row !== null) open.push(row);
	}

	const lines: string[] = [];
	lines.push('<!-- Generated by `bun run bug index`. Do not edit by hand. -->');
	lines.push('');
	lines.push('# Bugs');
	lines.push('');
	lines.push(`${open.length} open bug${open.length === 1 ? '' : 's'} of ${bugs.length} total.`);
	lines.push('Closed bugs (fixed / wontfix / duplicate) stay on disk for history but');
	lines.push('are excluded from this index.');
	lines.push('');
	lines.push('Author or mutate via `bun run bug` (see `scripts/bug.ts` for the CLI).');
	lines.push('');

	if (open.length === 0) {
		lines.push('## Per-product');
		lines.push('');
		lines.push('_No open bugs._');
		lines.push('');
		return `${lines.join('\n')}`;
	}

	// Group by product, then severity.
	const byProduct = new Map<WPProduct, OpenBugRow[]>();
	for (const row of open) {
		const arr = byProduct.get(row.product) ?? [];
		arr.push(row);
		byProduct.set(row.product, arr);
	}
	const productKeys = [...byProduct.keys()].sort((a, b) => productOrder(a) - productOrder(b));

	lines.push('## Per-product');
	lines.push('');
	for (const product of productKeys) {
		const rows = byProduct.get(product) ?? [];
		lines.push(`### ${PRODUCT_LABELS[product]} (open: ${rows.length})`);
		lines.push('');
		const bySeverity = new Map<BugSeverity, OpenBugRow[]>();
		for (const row of rows) {
			const arr = bySeverity.get(row.severity) ?? [];
			arr.push(row);
			bySeverity.set(row.severity, arr);
		}
		const sevKeys = [...bySeverity.keys()].sort((a, b) => severityOrder(a) - severityOrder(b));
		for (const sev of sevKeys) {
			lines.push(`#### ${SEVERITY_LABELS[sev]}`);
			lines.push('');
			const sevRows = (bySeverity.get(sev) ?? []).slice().sort((a, b) => a.id.localeCompare(b.id));
			for (const row of sevRows) {
				const prSuffix = row.discovered_pr !== null ? ` (PR #${row.discovered_pr})` : '';
				lines.push(`- [${row.id}](${row.id}.md) -- ${row.title}${prSuffix}`);
			}
			lines.push('');
		}
	}

	return lines.join('\n');
}
